### ISSUE TITLE
fixed, please delete

### ISSUE THREAD

**Issue by jhar8602** [phpvirtualbox/phpvirtualbox#103]
fixed

**Comment by h6w** [comment]
Please don't delete questions because others may have had the same problem and your solution may help others by making it searchable.  Thanks!

I've rolled your issue back to what I got in the email, but I'm also aware you revised it twice but I can't see that.

**Comment by jhar8602** [comment]
Well, I finally fixed it by adding the interface through the cli using:
        VBoxManage modifyvm "VM name" --nic<x> intnet

The virtualbox manual is a bit unclear, not telling what variable to put for <x>
using:
          VBoxManage modifyvm "VM name" --nic3 intnet   
 did the job.

Still wondering if phpvirtualbox should create an internal network automatically when selecting it in the webui
