### ISSUE TITLE
Missing bracket in vboxconnector.php

### ISSUE THREAD

**Issue by sqeeek** [phpvirtualbox/phpvirtualbox#110]
phpvirtualbox/endpoints/lib/vboxconnector.php
Line 3831
$this->session->machine->VRDEServer->setVRDEProperty('TCP/Address',($this->settings->vrdeaddress ? $this->settings->vrdeaddress : '127.0.0.1');

Should be $this->session->machine->VRDEServer->setVRDEProperty('TCP/Address',($this->settings->vrdeaddress ? $this->settings->vrdeaddress : '127.0.0.1')); <---two brackets right there

Apologies for not being able to submit a pull request or something, in a huge hurry.

**Comment by h6w** [comment]
My bad.  I should have spotted that during the pull request.  Thanks!
