### ISSUE TITLE
Option to view the virtual machine in HTML 5

### ISSUE THREAD

**Issue by GoNotCougsWA** [phpvirtualbox/phpvirtualbox#112]
I would really like if you guys add html 5 Option to view/move the virtual machine. I know it's possible.

**Comment by lapo-luchini** [comment]
If by "move" you mean change the order (or grouping) in the list of machines, it's already possibile.

**Comment by GoNotCougsWA** [comment]
What I am talking about is to view the virtual machine in HTML 5 and also, be able to control the virtual machine in HTML 5.

**Comment by h6w** [comment]
I think this may be a duplicate of issue #111

**Comment by GoNotCougsWA** [comment]
Your right! I didn't know know it was in phpvirtualbox already. lol.
