### ISSUE TITLE
Is the project dead ?

### ISSUE THREAD

**Issue by francesco2013** [phpvirtualbox/phpvirtualbox#113]
Hello,

Is this project dead ? How comes the latest release is from Feb 2016 ?

Thank you 

Francesco Fazio

**Comment by h6w** [comment]
I think you mean Feb 2018.  https://github.com/phpvirtualbox/phpvirtualbox/releases

**Comment by francesco2013** [comment]
Yes my apologizes. Thanks for keeping up the good work :)

**Comment by Neustradamus** [comment]
Can you confirm if the latest 5.2.x (EOL): https://www.virtualbox.org/wiki/Changelog-5.2: VirtualBox 5.2.44 (released July 14 2020)?
- https://github.com/phpvirtualbox/phpvirtualbox/tree/master
