### ISSUE TITLE
Permanently disable version mismatch error

### ISSUE THREAD

**Issue by der-eismann** [phpvirtualbox/phpvirtualbox#115]
Hey everyone,
thanks for your great work and continuing the project!
However we have a minor inconvenience at work because we use openSUSE 42.3 on our servers and are stuck with VirtualBox 5.1.32, so everytime we use it we get an error:

> This version of phpVirtualBox (5.2-0) is incompatible with VirtualBox 5.1.32_SUSE. You probably need to download the latest phpVirtualBox 5.1-x.

Since there is no phpvirtualbox 5.1 there is no fix in sight. 
For now I changed [a line](https://github.com/phpvirtualbox/phpvirtualbox/blob/develop/js/chooser.js#L722) from 
```
if(vers[0]+'.'+vers[1] != vStr) {
```
to
```
if(vers[0]+'.'+vers[1] == vStr) {
```
But maybe in the future you can include a checkbox that's setting a cookie `warning-acknowledged: 1` or something like that.

**Comment by h6w** [comment]
I had thought this, too.  I think it needs to be per user, also.

I'm wondering if we should instead do something like browsers do and stick a big red bar at the top as well/instead.

**Comment by marcelojannotti** [comment]
To accept old subversions in phpVitualBox 5.2 accept VirtuaBox 5.2,5.1,5.0, but not will accept phpVirtualBox 5.2 with VirtualBox 5.3.

Change in chooser.js

'				var vStr = $('#vboxPane').data('vboxConfig').phpvboxver.substring(0,$('#vboxPane').data('vboxConfig').phpvboxver.indexOf('-')).indexOf('.'));'
'				var vers = $('#vboxPane').data('vboxConfig').version.string.replace('_OSE','').split('.');'
'			if(vers[0] != vStr[0] || vers[1] > vStr[1]) {'
'					vboxAlert('This version of phpVirtualBox ('+$('#vboxPane').data('vboxConfig').phpvboxver+') is incompatible with VirtualBox ' + $('#vboxPane').data('vboxConfig').version.string + ". You probably need to <a href='https://github.com/phpvirtualbox/phpvirtualbox' target=_blank>download the latest phpVirtualBox " + vers[0]+'.'+vers[1] + "-x</a>.<p>See the Versioning section below the file list in the link for more information</p>",{'width':'auto'});'
'				}'
