### ISSUE TITLE
Phpvirtualbox on Nginx?

### ISSUE THREAD

**Issue by 4abhinavjain** [phpvirtualbox/phpvirtualbox#120]
HI,

I tried setting up phpvirtualbox with Nginx server (Nginx and php-fpm). I manage to start the UI and get the login page, however no matter what I do it always gives an error invalid username and password (I installed it as a non-root user).

Has anyone here successfully ran it with Nginx?

**Comment by tom077** [comment]
Hi,

If you managed to get the login screen, your Nginx server should be OK.

There are two different username/password used in phpvirtualbox:

- username/password from the linux account that runs vboxwebsrv (you provide it in config.php)

- username/password required to use the web gui

In the web gui, the default login is admin/admin. You can change it after your first login.

**Comment by 4abhinavjain** [comment]
Thanks for the help. Yes, I missed that the default login is admin/admin. I was using my admin password to login :

Thanks for your advice
