### ISSUE TITLE
Could not connect to host (http://127.0.0.1:18083/)

### ISSUE THREAD

**Issue by CYBER2412** [phpvirtualbox/phpvirtualbox#131]
i have a problem when i try to login with 
username: admin
password: admin

i get a error saying:
Could not connect to host (http://127.0.0.1:18083/)

and as Details i get:
"""
Exception Object
(
    [message:protected] => Could not connect to host (http://127.0.0.1:18083/)
    [string:Exception:private] => 
    [code:protected] => 64
    [file:protected] => C:\xampp\htdocs\endpoints\api.php
    [line:protected] => 134
    [trace:Exception:private] => Array
        (
        )

    [previous:Exception:private] => 
)
"""

can some wane please help?
its on windows 10

**Comment by CYBER2412** [comment]
thank you I've come a step further, but now he gives the error:

error logging in to vboxwebsrv

details:
"""
Exception Object
(
    [message:protected] => Error logging in to vboxwebsrv.
    [string:Exception:private] => 
    [code:protected] => 64
    [file:protected] => C:\xampp\htdocs\endpoints\api.php
    [line:protected] => 134
    [trace:Exception:private] => Array
        (
        )

    [previous:Exception:private] => 
)
"""

**Comment by tom077** [comment]
Have you edited the default config.php file in the phpvirtualbox folder?
You need at least :
```
var $username = 'vbox';
var $password = 'pass';
```

replace vbox by your windows username and pass by your password.

**Comment by CYBER2412** [comment]
thanks i fixed it
