### ISSUE TITLE
Blank site no login screen

### ISSUE THREAD

**Issue by HerrBeef** [phpvirtualbox/phpvirtualbox#135]
I'm stuck before login screen. it shows a loading popup. Then it goes away and blank site. Developertools dont print any error. error log from apache nothing either.
Version 5.2  newest virtualbox 5.2

**Comment by h6w** [comment]
Can you provide more information on your config?  It sounds like a generic apache misconfiguration to me.

**Comment by arvera** [comment]
What kind of info for the config are we looking for..? 

here is some info that might help.. but certanly not all of it.

```
$ ls -lsa /etc/apache2/mods-available/ |grep -i php
 4 -rw-r--r-- 1 root root   897 Oct 27  2015 php5.conf
 4 -rw-r--r-- 1 root root    59 Oct 27  2015 php5.load
 4 -rw-r--r-- 1 root root   867 Sep 13 14:44 php7.0.conf
 4 -rw-r--r-- 1 root root    79 Sep 13 14:44 php7.0.load
```
```
$more dir.conf 
<IfModule mod_dir.c>
	DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm index.php
</IfModule>

```


```
$perl -v

This is perl 5, version 22, subversion 1 (v5.22.1)
```

**Comment by h6w** [comment]
Are you having an issue @arvera?  Please open a separate issue if you are so we can deal with it separately.  This issue appears to be a simple apache misconfiguration.  We can't help if the OP doesn't provide more information. (And it looks like they've gone anyway.)
