### ISSUE TITLE
Add 6.0 support

### ISSUE THREAD

**Issue by hydrian** [phpvirtualbox/phpvirtualbox#136]
Add support for VirtualBox 6.0. It is currently in beta. Link for packages: http://download.virtualbox.org/virtualbox/6.0.0_BETA1/

**Comment by hydrian** [comment]
I can be an early adopter once to coding is done.

**Comment by h6w** [comment]
Done!  Pull from the develop tree.  Thanks!

**Comment by hydrian** [comment]
Pulled the most recent version and at least the version error is gone. I'll continue testing for other issues.

**Comment by tom077** [comment]
In theory, we also need to upgrade phpvirtualbox/endpoints/lib/vboxServiceWrappers.php which is automaticaly generated by a script from virtualbox SDK.

**Comment by e-alfred** [comment]
@h6w Any chance to get support for different graphics cards now supported by Virtualbox into phpvirtualbox?

**Comment by derekschrock** [comment]
> In theory, we also need to upgrade phpvirtualbox/endpoints/lib/vboxServiceWrappers.php which is automaticaly generated by a script from virtualbox SDK.

Looks like this should be done for the current release as well.  Best that I can tell we're lucky that anything changed or added since whatever version we have that breaks functionality.

I'd assume we can just download the SDK file and plop down sdk/bindings/webservice/php/lib/vboxServiceWrappers.php to endpoints/lib/vboxServiceWrappers.php?

**Comment by trasherdk** [comment]
Well, doing a diff between `vboxServiceWrappers.php` on the `current github dev` version and `sdk 6.0.4` version, tells me it's not that simple.

**Comment by derekschrock** [comment]
I can say that the missing (bool) casts are a problem.

**Comment by derekschrock** [comment]
> I can say that the missing (bool) casts are a problem.

However, this seems to be either the client's (phpvirtualbox) usage or vboxwebsrv not being able to convert a null to the proper boolean type.  This was 'fixed' by 911952b3140c.

Looks like these might be unfixed methods:

```
repos/phpvirtualbox/endpoints/lib/vboxconnector.php:                                            $m->mountMedium($name,$ma['port'],$ma['device'],(is_object($med) ? $med->handle : null),true);
repos/phpvirtualbox/endpoints/lib/vboxconnector.php:                            $this->session->machine->attachDevice(trans($DVDbusType,'UIMachineSettingsStorage'),1,0,'DVD',null);
repos/phpvirtualbox/endpoints/lib/vboxconnector.php:                    list($progress, $snapshotId) = $this->session->machine->takeSnapshot($args['name'], $args['description'], null);
repos/phpvirtualbox/endpoints/lib/vboxconnector.php:                                    $this->session->machine->mountMedium($r['controller'],$r['port'],$r['device'],null,true);
repos/phpvirtualbox/endpoints/lib/vboxconnector.php:            $this->session->machine->mountMedium($args['controller'],$args['port'],$args['device'],(is_object($med) ? $med->handle : null),true);
```

phpvirtualbox is already using `true/false` so might as well do the right thing in the client code?
At that point you should just be able drop the SDK file directly as new SDKs are released.

Can phpvirtualbox support both 5 and 6 via a `config.php` var and include either `vboxServiceWrappers5.php` or `vboxServiceWrappers6.php` via https://github.com/phpvirtualbox/phpvirtualbox/blob/develop/endpoints/lib/vboxconnector.php#L123

**Comment by pasha1st** [comment]
Please use my fork: https://github.com/pasha1st/phpvirtualbox-6

**Comment by jzedwards** [comment]
any planned release for 6.0.8? I can prob rollback to 6.0.6 to test, but if there is a 6.0.8 pending I would rather

**Comment by h6w** [comment]
Virtualbox doesn't make API changes between sub-point releases, so that means that phpvirtualbox only needs to release at every full point release.  So 6.0.6 and 6.0.8 will work with the 6.0 release.

**Comment by easyyu** [comment]
I have the same problem with installed virtual box v6.1.2.
I tried to update the phpVirtualBox 6.0-0 -/- VirtualBox 6.0.x compatible with latest version but I getting the same error.
What can I do to fix this?

**Comment by h6w** [comment]
Please try the current develop branch with Virtualbox 6.1.  We've been focusing our efforts on getting that to a release state.

**Comment by easyyu** [comment]
> 
> 
> Please try the current develop branch with Virtualbox 6.1. We've been focusing our efforts on getting that to a release state.

Yes..later I found.
Thx
