### ISSUE TITLE
VRDE don't work with phpVirtualBox 5.2.1 and VirtualBox 5.2.22

### ISSUE THREAD

**Issue by ArslanMarmozov** [phpvirtualbox/phpvirtualbox#140]
VRDE don't work with phpVirtualBox 5.2.1 and VirtualBox 5.2.22
Thats logs from VM startup.

00:00:00.209103 VRDP: Statistics created: [full], enabled: 0.
00:00:00.210463 VRDP: VRDP: VD: Frames=10 MinMS=15 MaxMS=300 HistoryMS=2000 VideoMS=300
00:00:00.210664 VRDP: Failed to query a property: 9, rc = VERR_NOT_SUPPORTED
00:02:00.211493 VRDP: Failed to start VRDP-IN thread, rc = VERR_TIMEOUT
00:02:00.211650 VRDP: TCP server closed.
00:02:00.212069 VRDE: Could not start the server rc = VERR_TIMEOUT
00:02:00.212096 VRDE: Failed: (VERR_TIMEOUT): Failed to launch the Remote Desktop Extension server (VERR_TIMEOUT)
00:02:00.212123 ERROR [COM]: aRC=NS_ERROR_FAILURE (0x80004005) aIID={872da645-4a9b-1727-bee2-5585105b9eed} aComponent={ConsoleWrap} aText={Failed to launch the Remote Desktop Extension server (VERR_TIMEOUT)}, preserve=false aResultDetail=0

**Comment by tom077** [comment]
Hi,

According to [phpvirtualbox Wiki](https://github.com/phpvirtualbox/phpvirtualbox/wiki#virtualbox--40---remote-console-access-note) : _In order to access a VM's console over RDP (via phpVirtualBox's console tab, or other RDP client) you must install the Oracle VM VirtualBox Extension Pack from: http://www.virtualbox.org/wiki/Downloads_

Did you install the the Oracle VM VirtualBox Extension Pack (Oracle_VM_VirtualBox_Extension_Pack-5.2.22.vbox-extpack)?

**Comment by ArslanMarmozov** [comment]
Hello. Thank You for answer. Yes I have installed Extension Pack.

**Comment by tom077** [comment]
OK.

What is the OS of your host server?


Can you give the result of the following commands :
(run as phpvirtualbox's user, see config.php)

`vboxmanage list extpacks`
`vboxmanage list systemproperties | grep "VRDE auth library"`
`vboxmanage list systemproperties | grep "Remote desktop ExtPack"`
`vboxmanage showvminfo 'your_vm_name' | grep VRDE` (replace 'your_vm_name')

**Comment by ArslanMarmozov** [comment]
CentOS Linux release 7.5.1804 (Core)

**vboxmanage list extpacks**
Extension Packs: 1
Pack no. 0:   Oracle VM VirtualBox Extension Pack
Version:      5.2.22
Revision:     126460
Edition:
Description:  USB 2.0 and USB 3.0 Host Controller, Host Webcam, VirtualBox RDP, PXE ROM, Disk Encryption, NVMe.
VRDE Module:  VBoxVRDP
Usable:       true
Why unusable:

**vboxmanage list systemproperties | grep "VRDE auth library"**
VRDE auth library:               VBoxAuth

**vboxmanage list systemproperties | grep "Remote desktop ExtPack"**
Remote desktop ExtPack:          Oracle VM VirtualBox Extension Pack

vboxmanage showvminfo 'RDP_VM' | grep VRDE
VRDE:            disabled
VRDE Connection:    not active

**Comment by h6w** [comment]
Hi,

That shows that the VRDE on that VM is disabled.  You need to go into the settings of the VM in PhpVB and select "Display" and then the "Remote Display" tab and tick "Enable Server".

**Comment by ArslanMarmozov** [comment]
`vboxmanage showvminfo 'Test VM' | grep VRDE`
VRDE:            enabled (Address vs1.servicecraft.ru, Ports 9000-9100, MultiConn: off, ReuseSingleConn: off, Authentication type: null)
VRDE property: TCP/Ports  = "9000-9100"
VRDE property: TCP/Address = "vs1.servicecraft.ru"
VRDE property: VideoChannel/Enabled = <not set>
VRDE property: VideoChannel/Quality = <not set>
VRDE property: VideoChannel/DownscaleProtection = <not set>
VRDE property: Client/DisableDisplay = <not set>
VRDE property: Client/DisableInput = <not set>
VRDE property: Client/DisableAudio = <not set>
VRDE property: Client/DisableUSB = <not set>
VRDE property: Client/DisableClipboard = <not set>
VRDE property: Client/DisableUpstreamAudio = <not set>
VRDE property: Client/DisableRDPDR = <not set>
VRDE property: H3DRedirect/Enabled = <not set>
VRDE property: Security/Method = <not set>
VRDE property: Security/ServerCertificate = <not set>
VRDE property: Security/ServerPrivateKey = <not set>
VRDE property: Security/CACertificate = <not set>
VRDE property: Audio/RateCorrectionMode = <not set>
VRDE property: Audio/LogPath = <not set>

When start VM, in log appears that output:

00:00:00.039445 Package type: LINUX_64BITS_EL_7
00:00:00.064190 Installed Extension Packs:
00:00:00.064205   Oracle VM VirtualBox Extension Pack (Version: 5.2.22 r126460; VRDE Module: VBoxVRDP)
00:00:00.065346 Console: Machine state changed to 'Starting'
00:00:00.069431 VRDP: Statistics created: [full], enabled: 0.
00:00:00.070582 VRDP: VRDP: VD: Frames=10 MinMS=15 MaxMS=300 HistoryMS=2000 VideoMS=300
00:00:00.070762 VRDP: Failed to query a property: 9, rc = VERR_NOT_SUPPORTED
00:00:02.919503 VRDP: TCP server failed to bind to a port: default 3389, range [9000-9100]
00:00:02.919600 VRDP: Failed to start VRDP-IN thread, rc = VERR_NET_ADDRESS_IN_USE
00:00:02.919757 VRDP: TCP server closed.
00:00:02.920310 VRDE: Warning: failed to launch VRDE server (VERR_NET_ADDRESS_IN_USE): VirtualBox Remote Desktop Extension server can't bind to the port(s): 9000-9100
00:00:02.943123 SUP: Opened VMMR0.r0 (/usr/lib/virtualbox/VMMR0.r0) at 0xXXXXXXXXXXXXXXXX.
00:00:02.946209 Guest OS type: 'RedHat_64'
00:00:02.950328 fHMForced=true - 64-bit guest

**Comment by ArslanMarmozov** [comment]
Ohhh.... I understand whats is going on...
My VRDE addresing configuration is conflict with new VRDE addressing scheme in phpVirtualBox.

`var $vrdeaddress = 'vs1.domain.tld'; // Configuration for remote access to VRDE using domain name.`

 In old versions this solution worked if in virtual host configured server and alias name in web server thats serv to phpVirtualBox. With new mechanism, I configure remote access to VRDE using this config variable and domain as value. But now is make conflict.

At now a don't have any idea how to fix it.

**Comment by ArslanMarmozov** [comment]
Temporary solution to configure remote access to VRDE using domain name with example:

**Example Data:**
**IP:** 192.168.1.1
**Domain:** vs1.domain.tld

First You need shutdown all existed Remote Display, then edit config.php in phpVirtualBox directory, and assing domain value to $vrdeaddress variable:

var $vrdeaddress = 'vs1.domain.tld'; // Configuration for remote access to VRDE using domain name.

Next You need assign internal IP address of VirtualBox machine with Your domain via /etc/hosts:

192.168.1.1 vs1.domain.tld

Finally, enable Remote Display via phpVirtualBox and that must work.

Thank You a lot for Your answers. I think it would not be bad to think together about a more productive solution to this problem.

**Comment by iamneo2416** [comment]
I have same issue, but my problem is far beyond this. I start to install a new vm via phpVirtualBox web interface. When I use Win10.iso and in the very first step, Installation, I used "Remote Display" and set to 9000 (127.0.0.1:9000), and I don't have clue how to use RDP to connect to this running installation my virtualbox host ip is 192.168.1.133. I tried to use **RDP** ( **192.168.1.133:3389, 192.168.1.133:9000** ), but non of them went success.  Can anyone tell me how to install vm using RDP ? Or should need to install some other tool to actiave RDP, right now I have realvnc.exe, windows mstsc.exe, remote desktop manager installed.

I can see "**Remote Display**" shows 
**Enable Server [V]  <== enable
Server Port: 9000
Authentication Method: none
Authentication Timeout: 5000**

**Comment by ArslanMarmozov** [comment]
> 
> 
> I have same issue, but my problem is far beyond this. I start to install a new vm via phpVirtualBox web interface. When I use Win10.iso and in the very first step, Installation, I used "Remote Display" and set to 9000 (127.0.0.1:9000), and I don't have clue how to use RDP to connect to this running installation my virtualbox host ip is 192.168.1.133. I tried to use **RDP** ( **192.168.1.133:3389, 192.168.1.133:9000** ), but non of them went success. Can anyone tell me how to install vm using RDP ? Or should need to install some other tool to actiave RDP, right now I have **realvnc.exe**, **windows mstsc.exe**, **remote desktop manager** installed. Nothing work ...
> 
> I can see "**Remote Display**" shows
> **Enable Server [V] <== enable Server Port: 9000 Authentication Method: none Authentication Timeout: 5000**
> 
> BUT no RDP connect success. Please help !!!!

You need configure phpVirtualBox via config.php.
Can You show current config.php file?

**Comment by VVD** [comment]
BTW, did you installed Extension Pack?
But it's work on Linux, OS X, Solaris and Windows only.
If you have VirtualBox OSE on host with other OS, then you need VNC plugin instead.

**Comment by ServerNinja** [comment]
What works for me:

```
// Set this to my headless Virtualbox IP address
var $consoleHost = '192.168.1.45';

// Define your range of VRDE ports here
var $vrdeports = '9100-9200';

// Set this to 0.0.0.0 (or the virtualbox server's IP address to be more specific...
// 0.0.0.0 ensures its listening on all interfaces)
var $vrdeaddress = '0.0.0.0';
```

**Comment by Neustradamus** [comment]
Can you confirm if the latest 5.2.x (EOL): https://www.virtualbox.org/wiki/Changelog-5.2: VirtualBox 5.2.44 (released July 14 2020)?
- https://github.com/phpvirtualbox/phpvirtualbox/tree/master
