### ISSUE TITLE
VirtualBox 5.2 support?

### ISSUE THREAD

**Issue by akosmaroy** [phpvirtualbox/phpvirtualbox#141]
Hi,

I just installed phpvirtualbox on ubuntu 18.04 with virtualbox coming from the stock ubuntu package:

```
$ VBoxManage --version
5.2.18_Ubuntur123745
$ VBoxManage list vms
"Ubuntu 18.04 LTS" {bf426c47-8193-4aab-863d-f57984d5a95b}
```

interestingly the latest 'develop' branch of phpvirtualbox doesn't seem so support this, it says:

```
This version of phpVirtualBox (6.0-0) is incompatible with VirtualBox 5.2.18_Ubuntu. You probably need to download the latest phpVirtualBox 5.2-x.

See the Versioning section below the file list in the link for more information
```

the latest phpvirtualbox release from zip 5.2.1.zip seems to not display that, but things don't seem to work, e.g. my VM is listed, but everything is disabled (e.g. can't stop / start / do any operations as these menu items are disabled in the phpvirtualbox UI, can't enter settings, the virtual media manager doesn't list any of the hard disks I've set up, etc.), see screenshots below.

what am I doing wrong?

Akos

![phpvirtualbox-vmm](https://user-images.githubusercontent.com/333140/49132449-ca909500-f2dc-11e8-99bf-a43402fac5ed.png)

![phpvirtualbox](https://user-images.githubusercontent.com/333140/49132483-e98f2700-f2dc-11e8-9ae1-bd3c3dc1721c.png)

**Comment by tom077** [comment]
Hi,

1/
The 'develop' branch exists for testing purposes.

As stated in issue #136, that branch is now ready to support Virtualbox 6.0 ( currently beta).


If you really want to use the 'develop' branch with virtualbox 5.2, you will need to manually edit your endpoint/lib/config.php :
```
define('PHPVBOX_VER', '5.2-1');
//define('PHPVBOX_VER', '6.0-0');
```


2/
According to your print Screen, you don't have any VM created for now.
The first row in the list is not a VM, just your host.

You need to create one : Button 'New', then follow the instructions.


![capture](https://user-images.githubusercontent.com/25565032/49162831-09017080-f32c-11e8-8027-280747a5685d.JPG)

**Comment by akosmaroy** [comment]
tnx. indeed changing the setting in the git / develop branch makes it work similarly to the zip

I actually have a VM defined with / for the vbox user:

```
vbox@box:~$ who am i
vbox     pts/2        2018-11-28 16:49 (::1)
vbox@box:~$ VBoxManage list vms
"Ubuntu 18.04 LTS" {bf426c47-8193-4aab-863d-f57984d5a95b}
vbox@box:~$ VBoxManage showvminfo "Ubuntu 18.04 LTS"
Name:            Ubuntu 18.04 LTS
Groups:          /
Guest OS:        Ubuntu (64-bit)
UUID:            bf426c47-8193-4aab-863d-f57984d5a95b
...
```

and I'm using this user in the phpvirtualbox config file:

```
/* Username / Password for system user that runs VirtualBox */
var $username = 'vbox';
var $password = 'XXX';
```

one peculiar thing is that the vboxweb service reports a different user?

```
# service vboxweb status
● vboxweb.service - VirtualBox Web Service
   Loaded: loaded (/lib/systemd/system/vboxweb.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-11-28 06:58:26 CET; 9h ago
  Process: 32075 ExecStart=/usr/bin/vboxwebsrv --pidfile /run/vboxweb.pid --background (code=exited, status=0/SUCCESS)
 Main PID: 32097 (vboxwebsrv)
    Tasks: 25 (limit: 4915)
   CGroup: /system.slice/vboxweb.service
           ├─32097 /usr/lib/virtualbox/vboxwebsrv --pidfile /run/vboxweb.pid --background
           ├─32100 /usr/lib/virtualbox/VBoxXPCOMIPCD
           └─32106 /usr/lib/virtualbox/VBoxSVC --auto-shutdown

Nov 28 06:58:26 box vboxwebsrv[32075]: 00:00:00.000556 main     OS Release: 4.15.0-36-generic
Nov 28 06:58:26 box vboxwebsrv[32075]: 00:00:00.000558 main     OS Version: #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018
Nov 28 06:58:26 box vboxwebsrv[32075]: 00:00:00.000631 main     DMI Product Name: ProLiant MicroServer Gen10
Nov 28 06:58:26 box vboxwebsrv[32075]: 00:00:00.000650 main     DMI Product Version: Rev B
Nov 28 06:58:26 box vboxwebsrv[32075]: 00:00:00.000826 main     Host RAM: 31627MB (30.8GB) total, 26718MB (26.0GB) avail
Nov 28 06:58:26 box vboxwebsrv[32075]: 00:00:00.000835 main     Executable: /usr/lib/virtualbox/vboxwebsrv
Nov 28 06:58:26 box vboxwebsrv[32075]: 00:00:00.000837 main     Process ID: 32075
Nov 28 06:58:26 box vboxwebsrv[32075]: 00:00:00.000839 main     Package type: LINUX_64BITS_GENERIC (OSE)
Nov 28 06:58:26 box systemd[1]: vboxweb.service: Supervising process 32097 which is not our child. We'll most likely not
Nov 28 06:58:26 box systemd[1]: Started VirtualBox Web Service.
```

see the end of the output above. this is despite:

```
# cat /etc/default/virtualbox
LOAD_VBOXDRV_MODULE=1
SHUTDOWN_USERS=""
SHUTDOWN=poweroff

VBOXWEB_USER=vbox
VBOXWEB_HOST=127.0.0.1

VBOXAUTOSTART_DB=/etc/vbox
VBOXAUTOSTART_CONFIG=/etc/vbox/autostart.cfg
```

wonder what I'm doing wrong...

**Comment by tom077** [comment]
Your vboxwebsrv process probably don't run as your user 'vbox'.

Can you paste the result of the cmd `cat /lib/systemd/system/vboxweb.service`?

**Comment by akosmaroy** [comment]
sure:

```
$ cat /lib/systemd/system/vboxweb.service
[Unit]
Description=VirtualBox Web Service
After=network.target

[Service]
Type=forking
ExecStart=/usr/bin/vboxwebsrv --pidfile /run/vboxweb.pid  --background
PIDFile=/run/vboxweb.pid

[Install]
WantedBy=multi-user.target
```

I tried to set User=vbox in the [Service] segment, but that results in a range of permission error messages and wouldn't start

**Comment by tom077** [comment]
You can create your own systemd service unit (or edit the default one, but it can be overridden by updates).

/etc/systemd/system/vboxweb-custom.service :

```
[Unit]
Description=VirtualBox Web Service
After=network.target

[Service]
Type=forking
User=vbox
RuntimeDirectory=vbox
ExecStart=/usr/bin/vboxwebsrv --pidfile /run/vbox/vboxwebsrv.pid --background
PIDFile=/run/vbox/vboxwebsrv.pid


[Install]
WantedBy=multi-user.target
```
Stop vboxweb.service and permanently disable autostart :

```
sudo systemctl stop vboxweb.service
sudo systemctl disable vboxweb.service
```
Start the new vboxwebsrv service and enable autostart :

```
sudo systemctl start vboxweb-custom.service
sudo systemctl enable vboxweb-custom.service
```

**Comment by akosmaroy** [comment]
tnx, perfect, now it works!

**Comment by Neustradamus** [comment]
@akosmaroy: It works with latest 5.2.x (EOL): https://www.virtualbox.org/wiki/Changelog-5.2: VirtualBox 5.2.44 (released July 14 2020)?
- https://github.com/phpvirtualbox/phpvirtualbox/tree/master
