### ISSUE TITLE
vboxweb :: usage of password hash

### ISSUE THREAD

**Issue by adriansev** [phpvirtualbox/phpvirtualbox#151]
Hi! IMHO is a security issue that clear text passwords are use in the php configuration..
Would be possible to use password hashes? Can VBOXWEB_AUTH_PWHASH parameter be used for authentication instead of clear text password of the user?

**Comment by adriansev** [comment]
no, is not ... if you give me your password i can ssh to your machine but if you give me the hash of your password (the one from /etc/shadow) i cannot .. and the problem stems for lack of information about https vboxweb

**Comment by brunoais** [comment]
Yes, I can't access through a system that will then hash what I give but it would still be the mechanism to login into virtualbox.
Do you mean to use that to prevent someone with access to the php files from getting the virtualbox login?

**Comment by brunoais** [comment]
Yes, I can't access through a system that will then hash what I give but it would still be the mechanism to login into virtualbox.
Do you mean to use that to prevent someone with access to the php files from getting the virtualbox login?

**Comment by adriansev** [comment]
so, no...  what i mean is that it is ALWAYS BAD PRACTICE to send over network clear text authentication   
and the problem that gives the biggest headache is that i did not find any information about making vboxweb work over ssl (https)   
any worm that scan/tcpdump the local (v)lan can get the clear text credentials that it should not get. i know there is always vpn/wireguard but the low hanging fruit would be to implement in phpvirtualbox the authentication with hash (that vboxweb seems to support) and if someone could document in wiki the configuration of https part of vboxweb (ignoring the certificate creation and signing because it is easily found on google)

**Comment by brunoais** [comment]
Oh, I see.
The missing HTTPS is, indeed, a complicated matter. I'm also pro in having documentation on setting up https.
phpvirtualbox (server side) uses a persistent connection with virtualbox, from what I got. It appeared to me it is not done through https, so I think, the only way of solving the communication eavesdropping between phpvirtualbox and virtualbox is by using a VPN.

**Comment by h6w** [comment]
This is a bit misdirected.  We don't maintain vboxweb.  That's part of Virtualbox.  phpvirtualbox presumes that it is only connected to a network you trust server-side.  If you're looking to lock down a network between phpvirtualbox and Virtualbox then I would suggest looking into GRE or VPN as suggested by @brunoais.

**Comment by adriansev** [comment]
On 1/13/19 2:16 AM, h6w wrote:
> This is a bit misdirected. We don't maintain vboxweb. That's part of 
> Virtualbox. phpvirtualbox presumes that it is only connected to a 
> network you trust server-side. If you're looking to lock down a network 
> between phpvirtualbox and Virtualbox then I would suggest looking into 
> GRE or VPN as suggested by @brunoais <https://github.com/brunoais>.
My issues had nothing to do with vboxweb but with the authentication 
part of phpvirtualbox to vboxweb. vboxweb have a setting named 
VBOXWEB_AUTH_PWHASH so i suspect that the authentication part can be 
done by using the passwordhash.
So, my feature request was to allow the authentication to be done by 
hash, so instead of 'password' from config.php to have a 'passwordhash'

Is it possible? Did i misinterpret the VBOXWEB_AUTH_PWHASH setting of 
vboxweb?

Thank you!

**Comment by h6w** [comment]
The only reference to that environment variable is in the script vboxweb-service.sh which is used to initialise vboxwebsrv during installation.  After that, you have to talk to vboxwebsrv as though you were an ordinary user.

**Comment by adriansev** [comment]
On 1/13/19 1:30 PM, h6w wrote:
> The only reference to that environment variable is in the script 
> vboxweb-service.sh which is used to initialise vboxwebsrv during 
> installation. After that, you have to talk to vboxwebsrv as though you 
> were an ordinary user.
umm, yes, i just found out that the hash option is used just for vrde 
authentication..

well, back to trying to make vboxweb work with https :(

thanks!
Adrian
