### ISSUE TITLE
Error message references sourceforge

### ISSUE THREAD

**Issue by lmorg** [phpvirtualbox/phpvirtualbox#169]
(First of all, if this is intentional then I apologise. It looked to me that this project was no longer being maintained on Source Forge)

While getting this to run I've encountered the following error message:

> An unknown PHP error occurred. This is most likely a syntax error in config.php in phpVirtualBox's folder. The most common errors are an unclosed quote or a missing semicolon in a configuration item that has been entered (e.g. location, username, or password).
>
> Depending on your PHP configuration, navigating directly to config.php in your web browser may display the PHP error message.
>
> If find that this is not the case, or have no idea what this error message means, please raise the issue at http://sourceforge.net/p/phpvirtualbox/discussion/help/

In the last paragraph the link points to sourceforge.net. Should that now be github?

**Comment by h6w** [comment]
Which version are you using?  All references to SF were removed about a year ago.

**Comment by lmorg** [comment]
I was pulling from the master branch. It looks like the changes have been made to develop branch and not merged back into master. I'm more than happy to work from develop if that is where you'd recommend but then the README would need to be updated as the instructions from there tell you to pull from master.

Thanks for the good work you guys that put into this, by the way. Open source can sometimes be a thankless job but I do really appreciate the effort :)

**Comment by chotaire** [comment]
That's because master branch is as old as VirtualBox 5.2. This is a confusion to everyone.

**Comment by lmorg** [comment]
Yeah, that was my point :)

I have a couple of options for organising git that would resolve this (if you're option to suggestions):

1. "tagging" the commit in master as supporting Vbox 5.x then merging your develop into master (so users can pull the old code if they need compatibility but git defaults to the latest version).

2. Or if develop is intended to be your one source of truth forevermore, then defining that as your default branch in GitHub.

Either solution is a < 5 min job (option 1 would be my preference because it preserves a develop branch for you to break things) and I'm happy to provide guides if your need them :)

**Comment by chotaire** [comment]
develop is the default branch. To verify, open an incognito tab in your browser and go to https://github.com/phpvirtualbox/phpvirtualbox ;)

**Comment by chotaire** [comment]
Oh, could you close this issue please? Thanks for your report.

**Comment by lmorg** [comment]
The [instructions on devop](https://github.com/phpvirtualbox/phpvirtualbox#installation-from-zip-file) still tell you to download from master though:

> 1. Download zip file from GitHub project site: https://github.com/phpvirtualbox/phpvirtualbox/archive/master.zip

Should read

> 1. Download zip file from GitHub project site: https://github.com/phpvirtualbox/phpvirtualbox/archive/develop.zip

Might be worth updating that in the README too

**Comment by chotaire** [comment]
I agree with you, this should be updated. @h6w can you look into this? 
In any case, that's a different issue. ;)

**Comment by lmorg** [comment]
My gut feeling is still that the master branch should still be updated to inform users that it's for an earlier version of VirtualBox (or better yet, tag it and merge develop into master). However that is a project design decision rather than a technical issue so I'll close this issue as requested. Thank you for your support and effort maintaining this project :)
