### ISSUE TITLE
WebUI dosent show IP address of guest anymore

### ISSUE THREAD

**Issue by ArpO1976** [phpvirtualbox/phpvirtualbox#170]
hi Folks,
Im using Virtualbox and phpvirtualbox fore some time. Running without any problems.
But now the WebUI dosent show the IP address of the running client anymore, and yes VM Tools are installed inside the client and running.
I can get the IP by running the commands
`[code]`
vbox@atom:~$ ./list_running_vms.sh
"Windows NT 4.0" {b1d200ea-d9d6-4b86-baea-f4c186e0c21e}

vbox@atom:~$ VBoxManage guestproperty enumerate "Windows NT 4.0" | grep IP
Name: /VirtualBox/GuestInfo/Net/0/V4/IP, value: 192.168.0.246, timestamp: 1558050060197658000, flags:
`[/code]`
on the console. How can i get the UI to show the IP address again?

**Comment by ArpO1976** [comment]
OMG fuckking god... forget it....
Solved...

**Comment by trasherdk** [comment]
What version of VirtualBox and phpvirtualbox are you running?

I don't see IP address, unless I put it in `description` of the guest.

**Comment by h6w** [comment]
Lol.  Thanks for letting us know you worked it out. :-)
