### ISSUE TITLE
can't enable multiple rdp connections

### ISSUE THREAD

**Issue by risticsasa011** [phpvirtualbox/phpvirtualbox#178]
Hello, 

I have a fresh install of VirtualBox 5.2.32 on CentOS, with Apache and phpvirtualbox (phpVirtualBox 5.2-1 -/- VirtualBox 5.2.x compatible).

Everything is working fine, except for the Remote Display > Extended Features: Allow Multiple Connections feature. I can check the box to enable this, and click Close to apply this setting (I presume...). When I enter the menu again, it's unchecked again. 

Any idea?
Thanks!

**Comment by chotaire** [comment]
I can confirm I am seeing the same issues with VirtualBox 6.0.12 and phpvirtualbox-develop.

**Comment by chotaire** [comment]
This works fine with VirtualBox-6.0.12 and phpvirtualbox-develop available at https://github.com/phpvirtualbox/phpvirtualbox/archive/develop.zip - Please update and once verified, close this issue. Thank you.
