### ISSUE TITLE
Footer edited to "b*tch" in wiki

### ISSUE THREAD

**Issue by peterberbec** [phpvirtualbox/phpvirtualbox#182]
I changed it, but some comedy genius changed the Wiki's footer to simply be the term for a female dog.

**Comment by h6w** [comment]
Wiku?  What's a wiku and what does it have to do with phpvirtualbox?

**Comment by chotaire** [comment]
This issue is a comedy which leaves the audience with the question why it is actually open.

**Comment by h6w** [comment]
I don't see how this issue relates to us and there has been no response from the OP after a month.  Closing.

**Comment by ahmgithubahm** [comment]
Well, it now reads '$803,30 cheaper than vSphere.'  Better than reported in this bug.  See the foot of any page on the Wiki of this repo.  Is the issue that this repo's wiki is editable by anyone?

**Comment by h6w** [comment]
Ah, now I understand.  I've changed the permissions on the wiki.  Thanks.
