### ISSUE TITLE
Support for VirtualBox 5.1

### ISSUE THREAD

**Issue by Polve** [phpvirtualbox/phpvirtualbox#19]

**Comment by Ignitor** [comment]
Second that

**Comment by nyvanga** [comment]
Me to. Although I am running 5.0-5 on my vbox 5.1.4 with no problems (except the warning about incompatibility)

**Comment by schast** [comment]
+1

**Comment by Tobii5** [comment]
Me too

**Comment by ezraholm50** [comment]
Would love it

**Comment by Kunzol** [comment]
Seems that no changes where made at the virtualbox api. 
I create a pull request for support of virtualbox 5.1 with minimal changes.

**Comment by imoore76** [comment]
That would be great!

**Comment by Kunzol** [comment]
Oops. There is a "d" missing. Correct is: 
I create**d** a pull request for support of virtualbox 5.1 with minimal changes.

**Comment by michaelpaesold** [comment]
For later reference, the pull request by @Kunzol is #22. It would be great to see this merged.

**Comment by Polve** [comment]
Hello, any news on the subject? I would like to migrate to vbox 5.1.x on my little server :-)

**Comment by dezlov** [comment]
+1

VirtualBox 5.1 has been out since July 2016.

**Comment by Kunzol** [comment]
For the moment, just check out my pull request #22 , which includes the patches for virtualbox 5.1.

**Comment by dezlov** [comment]
> For the moment, just check out my pull request #22 , which includes the patches for virtualbox 5.1.

Thanks for the patches.

I am just hoping that author will be able to make an official update soon.

**Comment by JamesBewley** [comment]
@Kunzol your pull request doesn't have any changes does that mean the current version has support for 5.1?

**Comment by michaelpaesold** [comment]
@JamesBewley Not sure what you mean, the PR #22 has changes as far as I can see: https://github.com/imoore76/phpvirtualbox/pull/22/files

**Comment by JamesBewley** [comment]
@michaelpaesold the change is to suppress the warning, there don't appear to be any code changes to support changes in the API?

**Comment by michaelpaesold** [comment]
@JamesBewley ah I see what you mean. Well as far as I understand, yes, the API didn't change in an incompatible way, the only thing needed was to update the WSDLs. Thats actually what the comment in the PR says. @Kunzol can you confirm?

**Comment by Kunzol** [comment]
Yes, this you can see and read in #22.

**Comment by h6w** [comment]
It's been almost a year since the last commit.  If it gets to a year (May 19, 2017), I'm going to fork it and push it upstream.

**Comment by Polve** [comment]
@h6w the project has been abandoned so you can proceed when you want.

**Comment by h6w** [comment]
Thanks.  I've started by asking the user @phpvirtualbox to close their empty account so that I can create an organisation with that name.  We'll see how that goes.

**Comment by BR0kEN-** [comment]
Please, fork it someone!

I'm currently using this dirty workaround to have it's working: https://github.com/BR0kEN-/cikit/blob/issue-25/matrix/roles/phpvirtualbox/tasks/remove-me.yml (instead of applying the patch).

**Comment by Kunzol** [comment]
I guess, this is what you are looking for: 

https://github.com/ezraholm50/phpvirtualbox

**Comment by h6w** [comment]
@BR0kEN- Yes.  There are many forks, see the list.  The owner of the other phpvirtualbox account agreed to shut down the account a month ago, but so far, it hasn't happened and they have stopped replying to the issue I raised.  https://github.com/phpvirtualbox/phpvirtualbox/issues/1

**Comment by imoore76** [comment]
Please leave my name as the initial author in all forks

**Comment by h6w** [comment]
@imoore76 Of course. :-)  We appreciate everything you've done. :-D

**Comment by h6w** [comment]
@imoore76 We now have a phpvirtualbox organisation!  :-D   I made you a member.  Are you able to transfer the repos to the organisation?

**Comment by h6w** [comment]
If anyone else wishes to be a contributor to the organisation, please let me know and I'll send you an invite. :-)

**Comment by Polve** [comment]
@imoore76 Can you please modify the README of the project linking the most updated fork?

**Comment by h6w** [comment]
@Polve This will be the most updated fork once the repos is transferred to the phpvirtualbox organisation (of which imoore76 is now an owner).

**Comment by BR0kEN-** [comment]
@h6w send an invite to me if possible. I'm going use `phpvirtualbox` with PHP 7.1 and pretty sure there's an additional work will be needed to complete the https://github.com/imoore76/phpvirtualbox/pull/24

**Comment by FunTimeCoding** [comment]
I might be interested in maintaining, too. I wonder if we could get together in a chat like Slack or a Skype conference.

**Comment by h6w** [comment]
@FunTimeCoding Funnily enough, there is an IRC channel registered at Freenode.  It seems to be currently owned by freenode-staff, but it does work.

**Comment by FunTimeCoding** [comment]
I joined. We can probably talk to staff to get it.

**Comment by Polve** [comment]
please guys, any news on the subject?
Is there a branch I can use for vbox 5.1.x?

**Comment by h6w** [comment]
@Polve Not yet.  I've only just taken over.  This issue is 8 months old.   I haven't yet obtained access to the distribution net.   Would you be interested in contributing to testing?

**Comment by Polve** [comment]
As a regular user I'll certainly report bugs.
Just installed ezraholm50 and it works fine with my vbox 5.1

**Comment by FunTimeCoding** [comment]
@h6w I want to contribute to testing, infrastructure, planning releases and making releases

**Comment by FunTimeCoding** [comment]
@h6w bump

**Comment by FunTimeCoding** [comment]
@h6w bump

**Comment by FunTimeCoding** [comment]
Since I'm being silently ignored for months, I'm going to give up on phpvirtualbox. You had the chance to revive this project. Now I'd rather stick to my own shell script wrappers around vboxmanage: https://github.com/FunTimeCoding/virtual-box-tools.

**Comment by e-alfred** [comment]
Is there any progress on the future of phpvirtualbox? I can see a lot of forks with multiple fixes for various issues that would be great to have in the official package.

**Comment by mrPsycho** [comment]
5.2 still works without problems with basic create/delete features.

**Comment by h6w** [comment]
We skipped 5.1 and have gone straight to 5.2.  Please see the 5.2-RC1 tag in develop.

**Comment by Neustradamus** [comment]
Can you confirm if the latest 5.2.x (EOL): https://www.virtualbox.org/wiki/Changelog-5.2: VirtualBox 5.2.44 (released July 14 2020)?
- https://github.com/phpvirtualbox/phpvirtualbox/tree/master
