### ISSUE TITLE
phpvirtualbox shows windows directory symbolic links not with a directory icon

### ISSUE THREAD

**Issue by jmar83** [phpvirtualbox/phpvirtualbox#193]
e.g. in the "Chose a virtual hard drive disk file..." dialog.

On my computer the (virtual) directory C:\users\xxx\VirtualBox VMs is a directory link to the RAID drive, and phpvirtualbox is not able to show it correctly on all its dialogs.

Same icon / behavior as a file, instead of directory!

Thank you for your feedbacks.

**Comment by jmar83** [comment]
problem is still persistent in https://github.com/phpvirtualbox/phpvirtualbox/releases/tag/5.2-1

**Comment by jmar83** [comment]
I tryed symlinks (from one partition to the other) just for as a workaround for the bug described on https://github.com/phpvirtualbox/phpvirtualbox/issues/194

If the bug on https://github.com/phpvirtualbox/phpvirtualbox/issues/194 is solved, i would say to show symlinks as folders is just a "nice to have"... up to you...

**Comment by jmar83** [comment]
"phpvirtualbox shows windows directory symbolic links not with a directory icon"

additional info: and they don't work like directories - it's not just an icon (gui) problems, it does not work..

**Comment by jmar83** [comment]
If there are some question, don't hesitate to ask..

**Comment by jmar83** [comment]
VirtualBox Version i use is 6.0.12...

**Comment by jmar83** [comment]
No answer??

**Comment by trasherdk** [comment]
I hope, you are aware, that you need to use the `develop` branch.
The tagged versions are all hopelessly outdated.

**Comment by jmar83** [comment]
I use the dev branch - Problem still persists...!!

**Comment by jmar83** [comment]
...
