### ISSUE TITLE
phpvirtualbox shows only content of C:\ in its file dialogs - instead of showing all drives

### ISSUE THREAD

**Issue by jmar83** [phpvirtualbox/phpvirtualbox#194]
phpvirtualbox shows only content of C:\ in its file dialogs - instead of showing all drives.

Is there an option to change the default drive from C:\ to X:\ as a workaround for that issue?

Thank you for your feedbacks.

**Comment by jmar83** [comment]
problem still persists in https://github.com/phpvirtualbox/phpvirtualbox/releases/tag/5.2-1 ..

**Comment by trasherdk** [comment]
Look in your `config.php` file.
```
// Restrict locations / folders
#var $browserRestrictFolders = array('D:\\','C:\\Users\\Ian'); // Or something like array('/home/vbox',/var/ISOs')
var $browserRestrictFolders = array('/home/vbox');

// Force use of local, web server based file browser instead of going through vboxwebsrv
#var $browserLocal = true;

// Disable file / folder browser.
#var $browserDisable = true;

// Disable Windows drive detection
#var $noWindowsDriveList = true;

// Just list all drives from C:\ - Z:\ without checking if they exist or not.
// This may be required on older Windows systems with more than one drive.
#var $forceWindowsAllDriveList = true;
```

**Comment by trasherdk** [comment]
On a side note. 5.2 should be marked as deprecated.
Moving to 6.0 is the primary focus at the moment.

**Comment by jmar83** [comment]
Thanks.

Yesterday i updated to 6.0.x, same behavior there...

Will try the config setting, it that works it's just a configuration issue! ;-)

**Comment by jmar83** [comment]
`var $noWindowsDriveList = false;` (so show all windows drives, instead of C: only? Default value seems to be "true"?) will result in the same dialog:

![Unbenannt](https://user-images.githubusercontent.com/24782840/64876889-80508880-d650-11e9-91f4-9cf1234fbefb.JPG)

**Comment by jmar83** [comment]
With `var $browserLocal = true;`, nothing is working anymore:

![Unbenddfghannt](https://user-images.githubusercontent.com/24782840/64877012-cc033200-d650-11e9-9490-1a84aed1c772.JPG)

:-(

**Comment by jmar83** [comment]
It would be a workaround to configure my R: (RAID) drive as root for file dialog, but to select any drives would be a big advantage!! ;-)

**Comment by jmar83** [comment]
Question: How can i configure so only the drive X:\ will be used for the file dialog instead of only using C:\

Thank you very much for your feedback.


Best regards,
Jan

**Comment by jmar83** [comment]
**A possible, sub-optimal workaround may be:**

var $noWindowsDriveList = false;
var $forceWindowsAllDriveList = true;

**Comment by jmar83** [comment]
VirtualBox Version i use is 6.0.12...

**Comment by jmar83** [comment]
"A possible, sub-optimal workaround may be"

There aren't any "clean" solutions for that issue yet??

**Comment by jmar83** [comment]
Problem still persists...!!

**Comment by jmar83** [comment]
Problem solved by myself, but i don't see any reason to explain here how i've done that... because i also never get appropriate anwsers from you... so sorry!!

**Comment by jmar83** [comment]
So closed now!! ;-)

**Comment by h6w** [comment]
Wow.  Won't spend 5 minutes examplaining your solution to a problem that might help others and yet you use software which takes other people 1000s of hours to build and maintain each year.  So ungrateful. :-|

**Comment by jmar83** [comment]
Yes, that's the life...;-)
