### ISSUE TITLE
Virtual HDD max size is 500GB?

### ISSUE THREAD

**Issue by jmar83** [phpvirtualbox/phpvirtualbox#195]
Virtual HDD max size is 500GB, i can't set up any HDDs they are bigger than that capacity...?

On the VirtualBox Windows GUI, there isn't a limitation like that - so it must be phpvirtualbox-specific.

Any solutions to solve that problem? Thank you for your feedbacks.

**Comment by h6w** [comment]
Can you send a screenshot?  I have no such limitation here.

**Comment by trasherdk** [comment]
How big do you want it?
![image](https://user-images.githubusercontent.com/5003891/64858106-a4ac6500-d650-11e9-8b72-bafada1e9a29.png)
**Notice the `1 TB` in the right input box, above .**

And after creation:
![image](https://user-images.githubusercontent.com/5003891/64858197-e76e3d00-d650-11e9-8c99-ee570d00a3bd.png)

And, here's what they looks like in the `Virtual Media Manager`
![image](https://user-images.githubusercontent.com/5003891/64858411-7d09cc80-d651-11e9-8632-9956dfcacd56.png)

**Comment by jmar83** [comment]
Oh, do i need to enter it manually? ;-)

**Comment by jmar83** [comment]
Will test it when install the next os...
