### ISSUE TITLE
Problems with re-using virtualbox disks (.vmdk), message "Already exists", even if the VM dir was deleted?

### ISSUE THREAD

**Issue by jmar83** [phpvirtualbox/phpvirtualbox#199]
So i found a "workaround" to bypass the problem described on https://github.com/phpvirtualbox/phpvirtualbox/issues/194 and got access on my R:\ drive, then i was thinking now we are ready to create a new VM without any hard disks , then using an existing .vmdk file the bypass the RDP address problem submitted on https://github.com/phpvirtualbox/phpvirtualbox/issues/196 ...

But no...:-(

1. I moved the .vmdk file from R:\VirtualBox VMs\MyVM\MyVM.vmdk to R:\MyVM.vmdk , then i tried to use it as a hard disk for the VM on R:\VirtualBox VMs\MyVM2\ ...

2. Then i got the "Already exists message" similar to "Already exists in R:\VirtualBox VMs\MyVM\MyVM.vmdk"

3. Then i deleted the "old" VM directory R:\VirtualBox VMs\MyVM\

4. Re-try to do the import.

5. Still the same message; you can see clearly that the dialog's message does not match to the content of R:\VirtualBox VMs\ ...:

I think this is a full-proof:

![Unbenannt](https://user-images.githubusercontent.com/24782840/65065273-62ea2a00-d982-11e9-8bd3-1032db3c90ea.JPG)

![Unbrgereeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeenannt](https://user-images.githubusercontent.com/24782840/65065052-fd963900-d981-11e9-9bad-1e2fe32abab4.JPG)

...you see nothing named Basis-Image... in that directory, that's it.

**Comment by jmar83** [comment]
And i also re-started the virtualbox web service AND used Ctrl-F5 (=bypass browser cache) in Chrome. Also also not solve that problem. Still the same one.

**Comment by jmar83** [comment]
VirtualBox Version i use is 6.0.12...

**Comment by h6w** [comment]
This is not a bug.  Virtualbox keeps an internal database of storage files in the Media Manager and then refers to it by that ID.  If you delete the file, the database still refers to it.  Look under File -> Virtual Media Manager and delete the reference to the file there.

**Comment by martijintro** [comment]
Thank you, will try it!!
