### ISSUE TITLE
Can't press '$' in RDP (Flash) console

### ISSUE THREAD

**Issue by jmar83** [phpvirtualbox/phpvirtualbox#202]
Can't press '$' in RDP (Flash) console, and the other charachter on that key (£, }) also don't work.

Why that, and how to solve that problem?

Thx for feedback.

**Comment by jmar83** [comment]
The keyboard i use is swiss german

**Comment by jmar83** [comment]
Problem das nothing to do with that (problem with many keys), most (all?) other keys work while the problem occurs: https://github.com/phpvirtualbox/phpvirtualbox/issues/203

**Comment by jmar83** [comment]
No answer??

**Comment by jmar83** [comment]
Problem still persists...!!

**Comment by martijintro** [comment]
???

**Comment by jmar83** [comment]
No anwser since almost 1 year - WTF?!?

**Comment by jmar83** [comment]
...
