### ISSUE TITLE
phpvirtualbox does not show cloned vms

### ISSUE THREAD

**Issue by martijintro** [phpvirtualbox/phpvirtualbox#207]
option: full clone

but the cloned vm exists on the file system, copy process is 100% done.

why it does not show??

regards, jan

**Comment by trasherdk** [comment]
Update to a supported version. Both VirtualBox and PHPVirtualBox.
I don't think anybody is working on those outdated versions.

**Comment by martijintro** [comment]
I think virtualbox 5.2.x is still supported and the development (updates..) is not stopped..?

Are your current phpvirtualbox versions compataible to it??

**Comment by trasherdk** [comment]
Maybe so, but that does not mean that somebody is working on PHPVirtualBox 5.0.x

The focus should be to get the current develop/master branch up to par with 6.0.x so a release can be tagged.

**Comment by martijintro** [comment]
ok thx, seems to work on my other server with both versions 6.x, virtualbox & phpvirtualbox..
