### ISSUE TITLE
Pointing Device in VM settings

### ISSUE THREAD

**Issue by dezlov** [phpvirtualbox/phpvirtualbox#21]
VirtualBox GUI contains a dropdown menu in VM settings to select a pointing device. Please add this option to phpVirtualBox. 

VM Settings > System > Motherboard > Pointing Device:
- PS/2 Mouse
- USB Tablet
- USB Multi-Touch Tablet

These settings were available since at least VirtualBox 5.0, but probably even earlier.

A command for modifying pointing device via VBoxManage:
`$ VBoxManage modifyvm --mouse <ps2|usb|usbtablet|usbmultitouch>`

![virtualbox-win-5.1.4-pointing-device](https://cloud.githubusercontent.com/assets/7993917/18082666/cf2186b8-6e97-11e6-9960-0af05a14883e.png)

![phpvirtualbox-5.0-5-no-pointing-device](https://cloud.githubusercontent.com/assets/7993917/18082670/d46fc9e0-6e97-11e6-9ec1-bfa4245565e8.png)

**Comment by TheFlipside** [comment]
please add this option to phpvirtualbox, by default new VMs are set to PS2 mouse which makes especially windows guests with a GUI almost unusable because the mouse jumps all over the place

**Comment by tom077** [comment]
Hi,
This feature already exists (but I don't know if it works well).
You need to uncomment a line in your config.php :
`var $enableAdvancedConfig = true;`

This add a new tab "Input" in VM Settings/General :

![capture](https://user-images.githubusercontent.com/25565032/33019567-2fb8fa74-cdfb-11e7-8519-57b09f078a9d.JPG)

**Comment by h6w** [comment]
If you think this shouldn't be an advanced config option, then I suggest opening another issue, but this is technically already implemented.  Thanks @tom077 for pointing that out! :D
