### ISSUE TITLE
phpvirtualbox: 500 Internal Server Error

### ISSUE THREAD

**Issue by fedqx** [phpvirtualbox/phpvirtualbox#229]
Hi, after the First installation, (this source: https://websiteforstudents.com/virtualbox-5-2-on-ubuntu-16-04-lts-server-headless/) and when I am trying to login tp phpvirtualbox with
 `http://<server-ip>/phpvirtualbox/` I am having this error:

![image](https://user-images.githubusercontent.com/34399010/76686212-e1224300-662a-11ea-866b-01fb7d8042e2.png)

When I click details:

`readyState: "4"`

`responseText: ""`

`status: "500"`

`statusText: "Internal Server Error"`

I can provide more info on demand.
Thanks!

**Comment by trasherdk** [comment]
That's a web-server error. 
`pgrep vboxwebsrv` can tell you if it's running.
`apachectl -t` might tell you more about apache config.

**Comment by fedqx** [comment]
There seems to be no problem other than:
 `AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message`
Could this be the issue?

**Comment by trasherdk** [comment]
Depends on how you are setup.
Are you in a `<VirtualHost www.example.com:port>` setup?
The `www.example.com` must resolve to the ip-address of your server.

**Comment by fedqx** [comment]
@trasherdk I just type http://123.456.789.0/phpvirtualbox
In the search bar. (of course that ip is an example, not real ip of the server)

**Comment by trasherdk** [comment]
Okay. Edit `http.conf` and change `ServerName` to something sensible.

**Comment by fedqx** [comment]
@trasherdk Ok, so VirtualBox version is `6.1` and I am not able to find the file `http.conf`

> ServerName to something sensible.

Btw, what does something sensible mean?

And my system neither has `http.conf` or `httpd.conf` (in /etc/apache2/)

**Comment by trasherdk** [comment]
I'm not going to guess your setup.
So, unless you volunteer sufficient information, you're on your own.

**Comment by fedqx** [comment]
@trasherdk If you can define "sufficient information", I can help.

**Comment by trasherdk** [comment]
The value of `ServerName` is dependent of the ip-address of the server, and `DNS`, or lack of DNS, pointing to that server.

I have no clue as to which OS you are running, what version of web-server you are using, or what your general setup looks like.

**Comment by fedqx** [comment]
Ubuntu Server 18.04 LTS headless, The server is local.

**Comment by trasherdk** [comment]
So, the conf file could be `/etc/apache2/apache2.conf`

> The server is local.

Local ? Is that feet or kilometers? Local in relation to what?

When in a console, run `hostname`, that will give you the ta,ta .. hostname of the box.

then run `host $(hostname)` that should give you the `IP-address` of the box.

then `host $(host $(hostname))` that should give you the `hostname` resolved to `IP-address` resolved back to `hostname`.

If that doesn't work, edit your `/etc/hosts` file. `man hosts` tells you what to do.

**Comment by marcos0877** [comment]
I have the same problem. 
I have a local server (dell with micro Xeon)
My So is ubuntu server 16.04 and apache
Host name is xxxx-xxxx and i run host $(hostname)
The result is  host xxxx-xxxx not found : 3(NXDOMAIN)
any suggestion?

I am very new in linux

**Comment by trasherdk** [comment]
You don't have valid DNS for your server.

`echo -e "10.0.1.2\tservername.example.com\tservername" >> /etc/hosts`

then `host servername` should return `10.0.1.2`.
