### ISSUE TITLE
Adding DVD device to SATA controller fails with "Validation constraint violation"

### ISSUE THREAD

**Issue by wpamllc** [phpvirtualbox/phpvirtualbox#234]
I created a new VM in phpVirtualBox 6.0-1.  Before booting the VM for the first time, I tried to add a DVD drive to the SATA controller, but received this error:

`Validation constraint violation: empty value provided where a value is required in element 'temporaryEject'`

The details appear in the attachment.
[validation-constraint-violation.txt](https://github.com/phpvirtualbox/phpvirtualbox/files/4546728/validation-constraint-violation.txt)

To "fix" things, I have to reboot my Virtualbox system and make adjustments to the controller with the GUI.

I can attach a hard drive using this same method, but not a DVD.

**Comment by weinic** [comment]
I have the same Problem 🤔

**Comment by trasherdk** [comment]
Version `6.0-1` ? Where did you find that? Last "release" was 5.2 in `Nov 9, 2018`.

**Comment by wpamllc** [comment]
Per @uschnidler, there is no release, but I'm using the latest master branch.  https://github.com/phpvirtualbox/phpvirtualbox/issues/210#issuecomment-629831791
