### ISSUE TITLE
how to configure proper rdp authentication, not only access if i call the web GUI from the server desktop / 127.0.0.1!?

### ISSUE THREAD

**Issue by jmar83** [phpvirtualbox/phpvirtualbox#236]
-> first of all, the rdp authentication method was empty... not "none", not "guest", not "external"...

then i saw that after i login in in the phpvirtualbox gui (last tab) after login was successful i was also able to login with mstsc.exe at the same time... and that WITHOUT AUTHENTICATION, WTF?!?

after that, i tried it with methods "external" or "guest" -> not success -> TCP timeout (or something like that?!?!)

after that i tryed to switch to "none" (i was thinking that was equivalent to the empry selectbox selection i described on the beginning on that post)... but there is not empty entry in the auth select box.

so the quintessence of my question: how to configure a PROPER authentication so i can access from "outside", not just from "127.0.0.1" or localhost...!!

is that possible with your software?

i mean i as same as proxmox do it, that is able to do that in a proper way - if you understand what i meant.

regards, jan

**Comment by jmar83** [comment]
So closed now..

**Comment by jmar83** [comment]
Closing was a mistaken action, so re-opened again! ;-)

**Comment by jmar83** [comment]
-> So problem still persists!!

**Comment by atx49559** [comment]
By my case, this command can fix that.
apt install php7.3-xml 

Debian 10
Apache 2.4.3.8
php v7.3.14

https://sourceforge.net/p/phpvirtualbox/discussion/help/thread/c566d48f7a/

**Comment by jmar83** [comment]
???

**Comment by h6w** [comment]
"Problem solved by myself, but i don't see any reason to explain here how i've done that... because i also never get appropriate anwsers from you... so sorry!!" --jmar83

**Comment by jmar83** [comment]
To be truthful:

To use Proxmox was the specific solution in that case...;-)

So long...

**Comment by e-alfred** [comment]
@jmar83 Same here. Getting rid of Virtualbox/Oracle and moving to KVM is like night and day.

**Comment by e-alfred** [comment]
@jmar83 Same here. Getting rid of Virtualbox/Oracle and moving to Proxmox/KVM is like night and day. Saying this as a former longtime heavy phpvirtualbox user.
