### ISSUE TITLE
Any updates ?

### ISSUE THREAD

**Issue by blackcrack** [phpvirtualbox/phpvirtualbox#244]
@all 
gives any updates on this coderepo or want anybody update it ?
well, in times of WebGL and other PHP7 Possibility's..

also a plugin for nextcloud could be possible to have a possible for using
it as testsystems launcher for a group or so..

best
Blacky

**Comment by h6w** [comment]
Closing as unclear what you're asking.  It looks like a set of feature requests but needs to be more specific.  We already support PHP7, WebGL is irrelevant, and NextCloud is outside our scope.
