### ISSUE TITLE
`$`-character will not be entered in flash vm screen

### ISSUE THREAD

**Issue by jayjupdhig** [phpvirtualbox/phpvirtualbox#246]
our root password contains a `$` character...

AND: Will phpvirtualbox die, if flash is not supported anymore end of year 2020? (I think so, i nobody cares about another technology.... proxmox has the ability to show the vm screen with native browser / html technlogies (canvas element??))

**Comment by martijintro** [comment]
???

**Comment by trasherdk** [comment]
I can't imagine why anybody would want to use flash for anything.
I can't imagine why anybody would want to waste time figuring out why it doesn't work.

I'm using Windows RDP client, if I for some reason can't ssh into the guest.

**Comment by martijintro** [comment]
really??

**Comment by martijintro** [comment]
No solution...?

**Comment by jayjupdhig** [comment]
problem is still pendent!!!

**Comment by h6w** [comment]
This is a configuration issue of your client.  $ works fine in my browser.  Flash was necessary because browsers don't allow direct TCP/UDP connections.  That's still true today.

**Comment by jayjupdhig** [comment]
So a chrome problem? My keyboard layout is correct, on other apps the `$` will be entered..
