### ISSUE TITLE
Remote Desktop IP

### ISSUE THREAD

**Issue by Lester702** [phpvirtualbox/phpvirtualbox#256]
I cannot change the remote desktop IP of any VM I create. It always ends up being 127.0.0.1. Is there any way to change it? Also is possible to port forward phpVirtualBox so I can use it from an outside network?

**Comment by blackcrack** [comment]
this is not a Network Support and Teaching and learning Station, learn something about network and start with VirtualBox, PHP-Virtualbox serve only a Web-Surface.

**Comment by Lester702** [comment]
> this is not a Network Support and Teaching and learning Station, learn something about network and start with VirtualBox, PHP-Virtualbox serve only a Web-Surface.
> 
> and this is not a issue from phpvirtualbox and should close . 

I do know something about networking and VirtualBox thank you very much. I don't know anything about PHP as it is a dog shit language that is basically Python wrapped in HTML

**Comment by blackcrack** [comment]
bulls*** this is an easy serverside html generation ,
if you not know how the Net work, should you a step back.. 
and i don't think, that you get an answer if you puke out some b..s..

have a nice day...

**Comment by klockren80** [comment]
Please keep a decent tone!

I added this line to /etc/default/virtualbox on my Ubuntu box which solved this issue:

`VBOXWEBSRV_HOST="0.0.0.0"`

**Comment by stianvis** [comment]
config.php
```php
/* Set the standard VRDE Port Number / Range, e.g. 1010-1020 or 1027 */
var $vrdeports = '9000-9100';
/* Set the default VRDE address, e.g. 192.168.1.1 */
#var $vrdeaddress = '192.168.1.1';
```

For existing machines you can change the address with
`VBoxManage modifyvm <uuid|vmname> --vrdeaddress 192.168.1.1`

**Comment by MrBanane6969** [comment]
wat
