### ISSUE TITLE
Ability to see host harddisk usage

### ISSUE THREAD

**Issue by miksch123** [phpvirtualbox/phpvirtualbox#258]
Hello,

so when I look at the details page of a VirtualBox server in phpvirtualbox I see stuff like host ram and its usage, CPU, Network Adapter and even info about the DVD/Floppy drive(s).

Now that might be a stupid question to ask, but is it possible to display the usage of a host's physical hard disk usage as well?

The reason why I am asking was because by being able to see how full those hard disks are I can then react accordingly by distributing the existing VMs more evenly or add additional physical Hard disks before the performance of the server takes a dip.

I also totally understand that sometimes such features if they get considered might not be feasible to add.

**Comment by h6w** [comment]
Actually this is a lot harder than it sounds.  I worked on another project that expected this (which was also irrelevant to that project) some time ago.  Determining which mount is the one on which phpvirtualbox exists is a project in itself (think symbolic links, hard links, partitions, LVM, etc.)  It has to be relevant.  Exposing all mounts would come up against things like snap which creates a mountpoint for each running application.  Then we have issues about clouds and filesystems - sometimes the drive isn't yours at all, and instead you "request" blocks until you the host says no.  Frequently the "drive" you're on is not physically on the machine but could be part of ZFS or LVM or an optic fibre network and may change rapidly.  This is really outside the scope.  I'd suggest using a host monitoring system relevant to your installation type.
