### ISSUE TITLE
Retire flash-based RDP client, replace with Guacamole

### ISSUE THREAD

**Issue by klockren80** [phpvirtualbox/phpvirtualbox#261]
Apache Guacamole is a very neat and modern RDP implementation in HTML5 that also supports VNC and SSH.

It requires a GUACD server in your network (available as a Docker image), so it will also require som new configuration directives to config.php

**Comment by baskinsy** [comment]
It would be nice to have a docker-compose setup for phpvirtualbox with Guacamole included. Apache and phpvirtualbox can be deployed in one container and guacd in another.

**Comment by blackcrack** [comment]
make it not dependent as docker .... b.. \*gnh*, 
learn to applications native configure and 
do not open secure relevant barn doors via docker .
HTML5 is nice and html5-tools also really well .. no question.. :)

**Comment by klockren80** [comment]
> It would be nice to have a docker-compose setup for phpvirtualbox with Guacamole included. Apache and phpvirtualbox can be deployed in one container and guacd in another.

Yes, but if you have multiple hypervisor servers with phpVirtualBox, you still only need one Guacd. Having a Guacd on each server may eat up more system resources than necessary.

**Comment by h6w** [comment]
I actually have this exact setup running, but Guacamole is outside the scope of the phpVirtualbox project because it's not based on PHP.
