### ISSUE TITLE
phpvirtualbox is not working when php 8.0.3 and higher is used

### ISSUE THREAD

**Issue by Dutchman01** [phpvirtualbox/phpvirtualbox#264]
phpvirtualbox is not working when freebsd 12.2 and php 8.0 and higher is used!

"An unknown PHP error occurred. This is most likely a syntax error in config.php in phpVirtualBox's folder. The most common errors are an unclosed quote or a missing semicolon in a configuration item that has been entered (e.g. location, username, or password)."
etc.

Please update internal code to support php 8 please

**Comment by stianvis** [comment]
Works fine on CentOS 8.3.2011 and PHP 8.0.1. You have the required packages installed? [Web server and PHP installation](https://github.com/phpvirtualbox/phpvirtualbox/wiki/Web-server-and-PHP-installation)

**Comment by Dutchman01** [comment]
PHP Version 8.0.1
 

System  FreeBSD xigmanas.local 12.2-RELEASE-p2 FreeBSD 12.2-RELEASE-p2 #0 r368991M: Mon Jan 11 19:04:34 CET 2021 root@dev_zoon01@xigmanas.com:/usr/obj/xigmanas/usr/src/amd64.amd64/sys/XIGMANAS-amd64 amd64  
Build Date  Jan 11 2021 21:31:47  
Build System  FreeBSD dev_zoon01@xigmanas.com 12.2-RELEASE-p1 FreeBSD 12.2-RELEASE-p1 GENERIC amd64  
Configure Command  './configure' '--with-pear' '--with-openssl' '--with-gettext' '--with-libxml' '--enable-mysqlnd' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-zlib-dir=/usr' '--with-config-file-path=/usr/local/etc' '--with-config-file-scan-dir=/usr/local/etc/php' '--enable-pdo' '--with-pdo-mysql=mysqlnd' '--with-pdo-sqlite=/usr/local' '--with-sqlite3' '--with-iconv-dir=/usr/local' '--with-bz2=/usr' '--with-curl' '--enable-exif' '--enable-gd' '--with-freetype' '--with-jpeg' '--enable-intl' '--with-ldap=/usr/local' '--enable-mbstring' '--with-mcrypt=/usr/local' '--with-gmp=/usr/local' '--enable-bcmath' '--enable-hash' '--with-mhash' '--enable-ftp' '--with-imap=/usr/local' '--with-imap-ssl=/usr' '--enable-soap' '--enable-sockets' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-tokenizer' '--with-xmlrpc' '--with-zip' '--with-zlib=/usr' '--enable-opcache' '--prefix=/usr/local' '--localstatedir=/var' '--mandir=/usr/local/man' '--infodir=/usr/local/share/info/' '--build=amd64-portbld-freebsd12.2' 'build_alias=amd64-portbld-freebsd12.2' 'PKG_CONFIG=pkgconf' 'LDFLAGS= -L/usr/lib -lcrypto -lssl -fstack-protector-strong ' 'LIBS=' 'CPP=cpp' 'CXXFLAGS=-O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -DLDAP_DEPRECATED -fno-strict-aliasing -DLIBICONV_PLUG -std=gnu++11 ' 'OPENSSL_CFLAGS=-I/usr/include' 'OPENSSL_LIBS=-L/usr/lib -lssl -lcrypto'  
Server API  CGI/FastCGI  
Virtual Directory Support  disabled  
Configuration File (php.ini) Path  /usr/local/etc  
Loaded Configuration File  /usr/local/etc/php.ini  
Scan this dir for additional .ini files  /usr/local/etc/php  
Additional .ini files parsed  /usr/local/etc/php/apcu.ini, /usr/local/etc/php/opcache.ini  
PHP API  20200930  
PHP Extension  20200930  
Zend Extension  420200930  
Zend Extension Build  API420200930,NTS  
PHP Extension Build  API20200930,NTS  
Debug Build  no  
Thread Safety  disabled  
Zend Signal Handling  enabled  
Zend Memory Manager  enabled  
Zend Multibyte Support  provided by mbstring  
IPv6 Support  enabled  
DTrace Support  disabled  
Registered PHP Streams https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip 
Registered Stream Socket Transports tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3 
Registered Stream Filters zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, convert.*, consumed, dechunk 

Zend logo This program makes use of the Zend Scripting Language Engine:
Zend Engine v4.0.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.1, Copyright (c), by Zend Technologies
 


Configuration

apcu

APCu Support  Enabled  
Version  5.1.19  
APCu Debugging  Disabled  
MMAP Support  Enabled  
MMAP File Mask  no value  
Serialization Support  php  
Build Date  Jan 11 2021 21:48:51  


Directive

Local Value

Master Value

apc.coredump_unmap Off Off 
apc.enable_cli On On 
apc.enabled On On 
apc.entries_hint 4096 4096 
apc.gc_ttl 3600 3600 
apc.mmap_file_mask no value no value 
apc.preload_path no value no value 
apc.serializer php php 
apc.shm_segments 1 1 
apc.shm_size 128M 128M 
apc.slam_defense Off Off 
apc.smart 0 0 
apc.ttl 86400 86400 
apc.use_request_time Off Off 

bcmath

BCMath support  enabled  


Directive

Local Value

Master Value

bcmath.scale 0 0 

bz2

BZip2 Support  Enabled  
Stream Wrapper support  compress.bzip2://  
Stream Filter support  bzip2.decompress, bzip2.compress  
BZip2 Version  1.0.8, 13-Jul-2019  

cgi-fcgi


Directive

Local Value

Master Value

cgi.check_shebang_line On On 
cgi.discard_path Off Off 
cgi.fix_pathinfo On On 
cgi.force_redirect On On 
cgi.nph Off Off 
cgi.redirect_status_env no value no value 
cgi.rfc2616_headers Off Off 
fastcgi.logging On On 

Core

PHP Version  8.0.1  


Directive

Local Value

Master Value

allow_url_fopen On On 
allow_url_include Off Off 
arg_separator.input & & 
arg_separator.output & & 
auto_append_file no value no value 
auto_globals_jit On On 
auto_prepend_file no value no value 
browscap no value no value 
default_charset UTF-8 UTF-8 
default_mimetype text/html text/html 
disable_classes no value no value 
disable_functions no value no value 
display_errors On On 
display_startup_errors On On 
doc_root no value no value 
docref_ext no value no value 
docref_root no value no value 
enable_dl On On 
enable_post_data_reading On On 
error_append_string no value no value 
error_log no value no value 
error_prepend_string no value no value 
error_reporting no value no value 
expose_php Off Off 
extension_dir /usr/local/lib/php/extensions/no-debug-non-zts-20200930 /usr/local/lib/php/extensions/no-debug-non-zts-20200930 
file_uploads On On 
hard_timeout 2 2 
highlight.comment #FF8000 #FF8000 
highlight.default #0000BB #0000BB 
highlight.html #000000 #000000 
highlight.keyword #007700 #007700 
highlight.string #DD0000 #DD0000 
html_errors Off Off 
ignore_repeated_errors Off Off 
ignore_repeated_source Off Off 
ignore_user_abort Off Off 
implicit_flush Off Off 
include_path .:/etc/inc:/usr/local/www .:/etc/inc:/usr/local/www 
input_encoding no value no value 
internal_encoding no value no value 
log_errors Off Off 
log_errors_max_len 1024 1024 
mail.add_x_header Off Off 
mail.force_extra_parameters no value no value 
mail.log no value no value 
max_execution_time 0 0 
max_file_uploads 20 20 
max_input_nesting_level 64 64 
max_input_time 180 180 
max_input_vars 1000 1000 
memory_limit 128M 128M 
open_basedir no value no value 
output_buffering 0 0 
output_encoding no value no value 
output_handler no value no value 
post_max_size 512M 512M 
precision 14 14 
realpath_cache_size 4096K 4096K 
realpath_cache_ttl 120 120 
register_argc_argv Off Off 
report_memleaks On On 
report_zend_debug Off Off 
request_order no value no value 
sendmail_from no value no value 
sendmail_path /usr/local/bin/msmtp -t /usr/local/bin/msmtp -t 
serialize_precision -1 -1 
short_open_tag Off Off 
SMTP localhost localhost 
smtp_port 25 25 
sys_temp_dir no value no value 
syslog.facility LOG_USER LOG_USER 
syslog.filter no-ctrl no-ctrl 
syslog.ident php php 
unserialize_callback_func no value no value 
upload_max_filesize 512M 512M 
upload_tmp_dir /var/tmp/ftmp /var/tmp/ftmp 
user_dir no value no value 
user_ini.cache_ttl 300 300 
user_ini.filename .user.ini .user.ini 
variables_order EGPCS EGPCS 
xmlrpc_error_number 0 0 
xmlrpc_errors Off Off 
zend.assertions 1 1 
zend.detect_unicode On On 
zend.enable_gc On On 
zend.exception_ignore_args Off Off 
zend.exception_string_param_max_len 15 15 
zend.multibyte Off Off 
zend.script_encoding no value no value 
zend.signal_check Off Off 

ctype

ctype functions  enabled  

curl

cURL support  enabled  
cURL Information  7.74.0  
Age  7  
Features  
AsynchDNS  Yes  
CharConv  No  
Debug  No  
GSS-Negotiate  No  
IDN  No  
IPv6  Yes  
krb4  No  
Largefile  Yes  
libz  Yes  
NTLM  Yes  
NTLMWB  Yes  
SPNEGO  Yes  
SSL  Yes  
SSPI  No  
TLS-SRP  Yes  
HTTP2  Yes  
GSSAPI  Yes  
KERBEROS5  Yes  
UNIX_SOCKETS  Yes  
PSL  No  
HTTPS_PROXY  Yes  
MULTI_SSL  No  
BROTLI  No  
Protocols  dict, file, ftp, ftps, gopher, http, https, imap, imaps, mqtt, pop3, pop3s, rtsp, smtp, smtps, telnet, tftp  
Host  amd64-portbld-freebsd12.2  
SSL Version  OpenSSL/1.1.1h  
ZLib Version  1.2.11  


Directive

Local Value

Master Value

curl.cainfo no value no value 

date

date/time support  enabled  
timelib version  2020.02  
"Olson" Timezone Database Version  2020.4  
Timezone Database  internal  
Default timezone  Europe/Amsterdam  


Directive

Local Value

Master Value

date.default_latitude 31.7667 31.7667 
date.default_longitude 35.2333 35.2333 
date.sunrise_zenith 90.833333 90.833333 
date.sunset_zenith 90.833333 90.833333 
date.timezone Europe/Amsterdam Europe/Amsterdam 

dom

DOM/XML  enabled  
DOM/XML API Version  20031129  
libxml Version  2.9.10  
HTML Support  enabled  
XPath Support  enabled  
XPointer Support  enabled  
Schema Support  enabled  
RelaxNG Support  enabled  

exif

EXIF Support  enabled  
Supported EXIF Version  0220  
Supported filetypes  JPEG, TIFF  
Multibyte decoding support using mbstring  enabled  
Extended EXIF tag formats  Canon, Casio, Fujifilm, Nikon, Olympus, Samsung, Panasonic, DJI, Sony, Pentax, Minolta, Sigma, Foveon, Kyocera, Ricoh, AGFA, Epson  


Directive

Local Value

Master Value

exif.decode_jis_intel JIS JIS 
exif.decode_jis_motorola JIS JIS 
exif.decode_unicode_intel UCS-2LE UCS-2LE 
exif.decode_unicode_motorola UCS-2BE UCS-2BE 
exif.encode_jis no value no value 
exif.encode_unicode ISO-8859-15 ISO-8859-15 

fileinfo

fileinfo support  enabled  
libmagic  539  

filter

Input Validation and Filtering  enabled  


Directive

Local Value

Master Value

filter.default unsafe_raw unsafe_raw 
filter.default_flags no value no value 

ftp

FTP support  enabled  
FTPS support  enabled  

gd

GD Support  enabled  
GD Version  bundled (2.1.0 compatible)  
FreeType Support  enabled  
FreeType Linkage  with freetype  
FreeType Version  2.10.4  
GIF Read Support  enabled  
GIF Create Support  enabled  
JPEG Support  enabled  
libJPEG Version  8  
PNG Support  enabled  
libPNG Version  1.6.37  
WBMP Support  enabled  
XBM Support  enabled  
BMP Support  enabled  
TGA Read Support  enabled  


Directive

Local Value

Master Value

gd.jpeg_ignore_warning 1 1 

gettext

GetText Support  enabled  

gmp

gmp support  enabled  
GMP version  6.2.1  

hash

hash support  enabled  
Hashing Engines  md2 md4 md5 sha1 sha224 sha256 sha384 sha512/224 sha512/256 sha512 sha3-224 sha3-256 sha3-384 sha3-512 ripemd128 ripemd160 ripemd256 ripemd320 whirlpool tiger128,3 tiger160,3 tiger192,3 tiger128,4 tiger160,4 tiger192,4 snefru snefru256 gost gost-crypto adler32 crc32 crc32b crc32c fnv132 fnv1a32 fnv164 fnv1a64 joaat haval128,3 haval160,3 haval192,3 haval224,3 haval256,3 haval128,4 haval160,4 haval192,4 haval224,4 haval256,4 haval128,5 haval160,5 haval192,5 haval224,5 haval256,5  

MHASH support  Enabled  
MHASH API Version  Emulated Support  

iconv

iconv support  enabled  
iconv implementation  unknown  
iconv library version  unknown  


Directive

Local Value

Master Value

iconv.input_encoding no value no value 
iconv.internal_encoding no value no value 
iconv.output_encoding no value no value 

imap

IMAP c-Client Version  2007f  
SSL Support  enabled  


Directive

Local Value

Master Value

imap.enable_insecure_rsh Off Off 

intl


Internationalization support

enabled

ICU version  68.2  
ICU Data version  68.2  
ICU Unicode version  13.0  


Directive

Local Value

Master Value

intl.default_locale no value no value 
intl.error_level 0 0 
intl.use_exceptions Off Off 

json

json support  enabled  

ldap

LDAP Support  enabled  
Total Links  0/unlimited  
API Version  3001  
Vendor Name  OpenLDAP  
Vendor Version  20456  


Directive

Local Value

Master Value

ldap.max_links Unlimited Unlimited 

libxml

libXML support  active  
libXML Compiled Version  2.9.10  
libXML Loaded Version  20910  
libXML streams  enabled  

mbstring

Multibyte Support  enabled  
Multibyte string engine  libmbfl  
HTTP input encoding translation  disabled  
libmbfl version  1.3.2  


mbstring extension makes use of "streamable kanji code filter and converter", which is distributed under the GNU Lesser General Public License version 2.1.


Multibyte (japanese) regex support  enabled  
Multibyte regex (oniguruma) version  6.9.6  


Directive

Local Value

Master Value

mbstring.detect_order no value no value 
mbstring.encoding_translation Off Off 
mbstring.http_input no value no value 
mbstring.http_output no value no value 
mbstring.http_output_conv_mimetypes ^(text/|application/xhtml\+xml) ^(text/|application/xhtml\+xml) 
mbstring.internal_encoding no value no value 
mbstring.language neutral neutral 
mbstring.regex_retry_limit 1000000 1000000 
mbstring.regex_stack_limit 100000 100000 
mbstring.strict_detection Off Off 
mbstring.substitute_character no value no value 

mysqli


MysqlI Support

enabled

Client API library version  mysqlnd 8.0.1  
Active Persistent Links  0  
Inactive Persistent Links  0  
Active Links  0  


Directive

Local Value

Master Value

mysqli.allow_local_infile Off Off 
mysqli.allow_persistent On On 
mysqli.default_host no value no value 
mysqli.default_port 3306 3306 
mysqli.default_pw no value no value 
mysqli.default_socket no value no value 
mysqli.default_user no value no value 
mysqli.max_links Unlimited Unlimited 
mysqli.max_persistent Unlimited Unlimited 
mysqli.reconnect Off Off 
mysqli.rollback_on_cached_plink Off Off 

mysqlnd


mysqlnd

enabled

Version  mysqlnd 8.0.1  
Compression  supported  
core SSL  supported  
extended SSL  supported  
Command buffer size  4096  
Read buffer size  32768  
Read timeout  86400  
Collecting statistics  Yes  
Collecting memory statistics  No  
Tracing  n/a  
Loaded plugins  mysqlnd,debug_trace,auth_plugin_mysql_native_password,auth_plugin_mysql_clear_password,auth_plugin_caching_sha2_password,auth_plugin_sha256_password  
API Extensions  mysqli,pdo_mysql  

openssl

OpenSSL support  enabled  
OpenSSL Library Version  OpenSSL 1.1.1h-freebsd 22 Sep 2020  
OpenSSL Header Version  OpenSSL 1.1.1h-freebsd 22 Sep 2020  
Openssl default config  /etc/ssl/openssl.cnf  


Directive

Local Value

Master Value

openssl.cafile no value no value 
openssl.capath no value no value 

pcre

PCRE (Perl Compatible Regular Expressions) Support  enabled  
PCRE Library Version  10.35 2020-05-09  
PCRE Unicode Version  13.0.0  
PCRE JIT Support  enabled  
PCRE JIT Target  x86 64bit (little endian + unaligned)  


Directive

Local Value

Master Value

pcre.backtrack_limit 1000000 1000000 
pcre.jit 1 1 
pcre.recursion_limit 100000 100000 

PDO


PDO support

enabled

PDO drivers  mysql, sqlite  

pdo_mysql


PDO Driver for MySQL

enabled

Client API version  mysqlnd 8.0.1  


Directive

Local Value

Master Value

pdo_mysql.default_socket /tmp/mysql.sock /tmp/mysql.sock 

pdo_sqlite


PDO Driver for SQLite 3.x

enabled

SQLite Library  3.34.0  

Phar


Phar: PHP Archive support

enabled

Phar API version  1.1.1  
Phar-based phar archives  enabled  
Tar-based phar archives  enabled  
ZIP-based phar archives  enabled  
gzip compression  enabled  
bzip2 compression  enabled  
Native OpenSSL support  enabled  

Phar based on pear/PHP_Archive, original concept by Davey Shafik.
Phar fully realized by Gregory Beaver and Marcus Boerger.
Portions of tar implementation Copyright (c) 2003-2009 Tim Kientzle. 


Directive

Local Value

Master Value

phar.cache_list no value no value 
phar.readonly On On 
phar.require_hash On On 

posix

POSIX support  enabled  

Reflection

Reflection  enabled  

session

Session Support  enabled  
Registered save handlers  files user  
Registered serializer handlers  php_serialize php php_binary  


Directive

Local Value

Master Value

session.auto_start Off Off 
session.cache_expire 180 180 
session.cache_limiter nocache nocache 
session.cookie_domain no value no value 
session.cookie_httponly 1 1 
session.cookie_lifetime 0 0 
session.cookie_path / / 
session.cookie_samesite no value no value 
session.cookie_secure 0 0 
session.gc_divisor 100 100 
session.gc_maxlifetime 1440 1440 
session.gc_probability 1 1 
session.lazy_write On On 
session.name PHPSESSID PHPSESSID 
session.referer_check no value no value 
session.save_handler files files 
session.save_path /tmp /tmp 
session.serialize_handler php php 
session.sid_bits_per_character 5 5 
session.sid_length 48 48 
session.upload_progress.cleanup On On 
session.upload_progress.enabled On On 
session.upload_progress.freq 1% 1% 
session.upload_progress.min_freq 1 1 
session.upload_progress.name PHP_SESSION_UPLOAD_PROGRESS PHP_SESSION_UPLOAD_PROGRESS 
session.upload_progress.prefix upload_progress_ upload_progress_ 
session.use_cookies 1 1 
session.use_only_cookies 1 1 
session.use_strict_mode 0 0 
session.use_trans_sid 0 0 

SimpleXML

SimpleXML support  enabled  
Schema support  enabled  

soap

Soap Client  enabled  
Soap Server  enabled  


Directive

Local Value

Master Value

soap.wsdl_cache 1 1 
soap.wsdl_cache_dir /tmp /tmp 
soap.wsdl_cache_enabled On On 
soap.wsdl_cache_limit 5 5 
soap.wsdl_cache_ttl 86400 86400 

sockets

Sockets Support  enabled  

SPL


SPL support

enabled

Interfaces  OuterIterator, RecursiveIterator, SeekableIterator, SplObserver, SplSubject  
Classes  AppendIterator, ArrayIterator, ArrayObject, BadFunctionCallException, BadMethodCallException, CachingIterator, CallbackFilterIterator, DirectoryIterator, DomainException, EmptyIterator, FilesystemIterator, FilterIterator, GlobIterator, InfiniteIterator, InvalidArgumentException, IteratorIterator, LengthException, LimitIterator, LogicException, MultipleIterator, NoRewindIterator, OutOfBoundsException, OutOfRangeException, OverflowException, ParentIterator, RangeException, RecursiveArrayIterator, RecursiveCachingIterator, RecursiveCallbackFilterIterator, RecursiveDirectoryIterator, RecursiveFilterIterator, RecursiveIteratorIterator, RecursiveRegexIterator, RecursiveTreeIterator, RegexIterator, RuntimeException, SplDoublyLinkedList, SplFileInfo, SplFileObject, SplFixedArray, SplHeap, SplMinHeap, SplMaxHeap, SplObjectStorage, SplPriorityQueue, SplQueue, SplStack, SplTempFileObject, UnderflowException, UnexpectedValueException  

sqlite3


SQLite3 support

enabled

SQLite Library  3.34.0  


Directive

Local Value

Master Value

sqlite3.defensive On On 
sqlite3.extension_dir no value no value 

standard

Dynamic Library Support  enabled  
Path to sendmail  /usr/local/bin/msmtp -t  


Directive

Local Value

Master Value

assert.active On On 
assert.bail Off Off 
assert.callback no value no value 
assert.exception On On 
assert.warning On On 
auto_detect_line_endings Off Off 
default_socket_timeout 60 60 
from no value no value 
session.trans_sid_hosts no value no value 
session.trans_sid_tags a=href,area=href,frame=src,form= a=href,area=href,frame=src,form= 
unserialize_max_depth 4096 4096 
url_rewriter.hosts no value no value 
url_rewriter.tags form= form= 
user_agent no value no value 

sysvmsg

sysvmsg support  enabled  

sysvsem

sysvsem support  enabled  

sysvshm

sysvshm support  enabled  

tokenizer

Tokenizer Support  enabled  

xml

XML Support  active  
XML Namespace Support  active  
libxml2 Version  2.9.10  

xmlreader

XMLReader  enabled  

xmlwriter

XMLWriter  enabled  

Zend OPcache

Opcode Caching  Up and Running  
Optimization  Enabled  
SHM Cache  Enabled  
File Cache  Disabled  
JIT  Not Available  
Startup  OK  
Shared memory model  mmap  
Cache hits  24  
Cache misses  5  
Used memory  8955792  
Free memory  125261936  
Wasted memory  0  
Interned Strings Used memory  418640  
Interned Strings Free memory  5872368  
Cached scripts  5  
Cached keys  7  
Max keys  7963  
OOM restarts  0  
Hash keys restarts  0  
Manual restarts  0  


Directive

Local Value

Master Value

opcache.blacklist_filename no value no value 
opcache.consistency_checks 0 0 
opcache.dups_fix Off Off 
opcache.enable On On 
opcache.enable_cli On On 
opcache.enable_file_override Off Off 
opcache.error_log no value no value 
opcache.file_cache no value no value 
opcache.file_cache_consistency_checks On On 
opcache.file_cache_only Off Off 
opcache.file_update_protection 2 2 
opcache.force_restart_timeout 180 180 
opcache.huge_code_pages Off Off 
opcache.interned_strings_buffer 8 8 
opcache.lockfile_path /tmp /tmp 
opcache.log_verbosity_level 1 1 
opcache.max_accelerated_files 4000 4000 
opcache.max_file_size 0 0 
opcache.max_wasted_percentage 5 5 
opcache.memory_consumption 128 128 
opcache.opt_debug_level 0 0 
opcache.optimization_level 0x7FFEBFFF 0x7FFEBFFF 
opcache.preferred_memory_model no value no value 
opcache.preload no value no value 
opcache.preload_user no value no value 
opcache.protect_memory Off Off 
opcache.record_warnings Off Off 
opcache.restrict_api no value no value 
opcache.revalidate_freq 60 60 
opcache.revalidate_path Off Off 
opcache.save_comments On On 
opcache.use_cwd On On 
opcache.validate_permission Off Off 
opcache.validate_root Off Off 
opcache.validate_timestamps On On 

zip

Zip  enabled  
Zip version  1.19.2  
Libzip version  1.7.3  
BZIP2 compression  Yes  
XZ compression  Yes  
ZSTD compression  No  
AES-128 encryption  Yes  
AES-192 encryption  Yes  
AES-256 encryption  Yes  

zlib


ZLib Support

enabled

Stream Wrapper  compress.zlib://  
Stream Filter  zlib.inflate, zlib.deflate  
Compiled Version  1.2.11  
Linked Version  1.2.11  


Directive

Local Value

Master Value

zlib.output_compression On On 
zlib.output_compression_level -1 -1 
zlib.output_handler no value no value 

Additional Modules


Module Name


Environment


Variable

Value

PATH  /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin  
PHP_FCGI_CHILDREN  5  
PHP_FCGI_MAX_REQUESTS  1000  

PHP Variables


Variable

Value

$_SERVER['PATH'] /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin 
$_SERVER['PHP_FCGI_CHILDREN'] 5 
$_SERVER['PHP_FCGI_MAX_REQUESTS'] 1000 
$_SERVER['PATH_TRANSLATED'] /mnt/Data/Data/WWW 
$_SERVER['ORIG_SCRIPT_FILENAME'] /mnt/Data/Data/WWW/phpinfo.php/ 
$_SERVER['HTTP_CONNECTION'] Keep-Alive 
$_SERVER['HTTP_HOST'] www.zoonsnas.nl 
$_SERVER['HTTP_ACCEPT_ENCODING'] gzip, deflate 
$_SERVER['HTTP_USER_AGENT'] Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko 
$_SERVER['HTTP_ACCEPT_LANGUAGE'] nl-NL,nl;q=0.8,en-US;q=0.5,en;q=0.2 
$_SERVER['HTTP_ACCEPT'] text/html, application/xhtml+xml, image/jxr, */* 
$_SERVER['REMOTE_PORT'] 50424 
$_SERVER['REMOTE_ADDR'] 192.168.1.232 
$_SERVER['SERVER_NAME'] www.zoonsnas.nl 
$_SERVER['SERVER_ADDR'] 192.168.1.238 
$_SERVER['SERVER_PORT'] 80 
$_SERVER['REQUEST_SCHEME'] http 
$_SERVER['GATEWAY_INTERFACE'] CGI/1.1 
$_SERVER['SERVER_SOFTWARE'] webserv 
$_SERVER['SERVER_PROTOCOL'] HTTP/1.1 
$_SERVER['REQUEST_METHOD'] GET 
$_SERVER['DOCUMENT_ROOT'] /mnt/Data/Data/WWW 
$_SERVER['SCRIPT_FILENAME'] /mnt/Data/Data/WWW/phpinfo.php 
$_SERVER['SCRIPT_NAME'] /phpinfo.php 
$_SERVER['REDIRECT_STATUS'] 200 
$_SERVER['REQUEST_URI'] /phpinfo.php 
$_SERVER['QUERY_STRING'] no value 
$_SERVER['CONTENT_LENGTH'] 0 
$_SERVER['FCGI_ROLE'] RESPONDER 
$_SERVER['PHP_SELF'] /phpinfo.php 
$_SERVER['REQUEST_TIME_FLOAT'] 1610491198.111 
$_SERVER['REQUEST_TIME'] 1610491198 
$_ENV['PATH'] /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin 
$_ENV['PHP_FCGI_CHILDREN'] 5 
$_ENV['PHP_FCGI_MAX_REQUESTS'] 1000 
$_ENV['PATH_TRANSLATED'] /mnt/Data/Data/WWW 
$_ENV['ORIG_SCRIPT_FILENAME'] /mnt/Data/Data/WWW/phpinfo.php/ 
$_ENV['HTTP_CONNECTION'] Keep-Alive 
$_ENV['HTTP_HOST'] www.zoonsnas.nl 
$_ENV['HTTP_ACCEPT_ENCODING'] gzip, deflate 
$_ENV['HTTP_USER_AGENT'] Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko 
$_ENV['HTTP_ACCEPT_LANGUAGE'] nl-NL,nl;q=0.8,en-US;q=0.5,en;q=0.2 
$_ENV['HTTP_ACCEPT'] text/html, application/xhtml+xml, image/jxr, */* 
$_ENV['REMOTE_PORT'] 50424 
$_ENV['REMOTE_ADDR'] 192.168.1.232 
$_ENV['SERVER_NAME'] www.zoonsnas.nl 
$_ENV['SERVER_ADDR'] 192.168.1.238 
$_ENV['SERVER_PORT'] 80 
$_ENV['REQUEST_SCHEME'] http 
$_ENV['GATEWAY_INTERFACE'] CGI/1.1 
$_ENV['SERVER_SOFTWARE'] webserv 
$_ENV['SERVER_PROTOCOL'] HTTP/1.1 
$_ENV['REQUEST_METHOD'] GET 
$_ENV['DOCUMENT_ROOT'] /mnt/Data/Data/WWW 
$_ENV['SCRIPT_FILENAME'] /mnt/Data/Data/WWW/phpinfo.php 
$_ENV['SCRIPT_NAME'] /phpinfo.php 
$_ENV['REDIRECT_STATUS'] 200 
$_ENV['REQUEST_URI'] /phpinfo.php 
$_ENV['QUERY_STRING'] no value 
$_ENV['CONTENT_LENGTH'] 0 
$_ENV['FCGI_ROLE'] RESPONDER

**Comment by stianvis** [comment]
What are your virtualbox and phpvirtualbox versions?

**Comment by Dutchman01** [comment]
phpvirtualbox-5.2.1 see https://www.freebsd.org/cgi/ports.cgi?query=phpvirtualbox&stype=name&sektion=all

and virtualbox-ose-5.2.44_4 see https://www.freebsd.org/cgi/ports.cgi?query=virtualbox-ose&stype=name&sektion=all

**Comment by stianvis** [comment]
Not sure what's wrong. I'm not that familiar with FreeBSD but I installed this
`virtualbox-ose-nox11 apache24 mod_php80 php80 php80-simplexml php80-soap php80-xml php80-session`
and
`https://github.com/phpvirtualbox/phpvirtualbox/archive/5.2-1.zip`
on a fresh FreeBSD 12.2 install and it seems to be working.

**Comment by Dutchman01** [comment]
What i have found on my setup to make it work!

When i go to /phpvirtualbox/endpoints/lib
edit language.php
in line 62 and so on

 		// No lang file found
 		} else {
 			$lang = 'en';
 			@define('VBOXLANG', $lang);
 			self::$langdata['contexts'] = array();
 			return;
 		}
 after this , I added manual
 		$lang = "nl";

so, whatever happened to $lang before, it is now set to "de"
and login is possible again.

to me it proves there is a bug in getting proper en language and popup a working error free login screen.

workaround 2:
I copyd all from nl.xml and past in into en.xml in phpvirtualbox/languages and saved the file with en translated strings again.

Now also the en login works again and i can login.

and the message disappear
"An unknown PHP error occurred. This is most likely a syntax error in config.php in phpVirtualBox's folder. The most common errors are an unclosed quote or a missing semicolon in a configuration item that has been entered (e.g. location, username, or password)."

**Comment by ms49434** [comment]
In endpoints/lib/language.php line 77/78, the issue is that $arrXml is an empty array when english language is selected and therefore doesn't contain key 'context':

72
73		$xmlObj = simplexml_load_string(@file_get_contents(VBOX_BASE_LANG_DIR.'/'.$lang.'.xml'));
74		$arrXml = $this->objectsIntoArray($xmlObj);
75
76		$lang = array();
77		if(!@$arrXml['context'][0]) $arrXml['context'] = array($arrXml['context']);
78		foreach($arrXml['context'] as $c) {

The fix is dead simple:
72
73		$xmlObj = simplexml_load_string(@file_get_contents(VBOX_BASE_LANG_DIR.'/'.$lang.'.xml'));
74		$arrXml = $this->objectsIntoArray($xmlObj);
75-
75+		if(!array_key_exists('context',$arrXml)) return;
76		$lang = array();
77		if(!@$arrXml['context'][0]) $arrXml['context'] = array($arrXml['context']);
78		foreach($arrXml['context'] as $c) {

This works with PHP 7 as well.

**Comment by Dutchman01** [comment]
issue closed see https://github.com/phpvirtualbox/phpvirtualbox/pull/292
