### ISSUE TITLE
Generate RDP file

### ISSUE THREAD

**Issue by klockren80** [phpvirtualbox/phpvirtualbox#265]
With Flash going away, phpVirtualBox should instead generate an RDP file that will be downloaded by the user's browser and opened with the default RDP client software. This will allow seamless integration between phpVirtualBox and the default RDP client on the user's computer.

In its simplest form, it could look like

```
full address:s:172.30.8.1:3392
compression:i:1
displayconnectionbar:i:1
protocol:i:4
```
But connection parameters such as authentication could easily be added.

Maybe this could end the RDP threads/discussions here?

**Comment by stianvis** [comment]
click on the "Remote Desktop Server Port" link in display to download the rdp file.
