### ISSUE TITLE
Error Fetching http headers (http://127.0.0.1:18083/)

### ISSUE THREAD

**Issue by luciano202** [phpvirtualbox/phpvirtualbox#266]
xception Object
(
    [message:protected] => Error Fetching http headers (http://127.0.0.1:18083/)
    [string:Exception:private] => 
    [code:protected] => 64
    [file:protected] => /var/www/html/phpvirtualbox/endpoints/api.php
    [line:protected] => 134
    [trace:Exception:private] => Array
        (
        )

    [previous:Exception:private] => 
)
se puderem ajudar nesse bug

**Comment by luciano202** [comment]
alguém tem a solução!?

**Comment by h6w** [comment]
This is a configuration error whcih we refer to in https://github.com/phpvirtualbox/phpvirtualbox/wiki/Common-phpVirtualBox-Errors-and-Issues#looks-like-we-got-no-xml-document

Simply, 18083 is the port for vboxwebsrv so it looks like you don't have vboxwebsrv running.

See https://github.com/phpvirtualbox/phpvirtualbox/wiki#installing-phpvirtualbox for proper configuration, or refer to the install script in https://github.com/phpvirtualbox/phpvirtualbox/blob/develop/packaging/install-scripts/install.bash
