### ISSUE TITLE
Unable to switch servers

### ISSUE THREAD

**Issue by coyotenq** [phpvirtualbox/phpvirtualbox#267]
A couple of days ago, i noticed that switching servers is not working.
I was trying to fix this, but my programming skills are not enough.

Anyone with this issue? Any idea of how to track and solve it?

Thanks in advance!

**Comment by httkl** [comment]
Same problem here (openSUSE Leap 15.2). I've seen php 7.4.6 +  modules was updated some days ago. Might be the reason?

**Comment by VVD** [comment]
Same here: FreeBSD 12.1 and 12.2 amd64, php 7.4.14 (updated from 7.4.13 10th of January, but found this issue several days ago only), phpvirtualbox 5.2-1.
I'll try to downgrade php.

**Comment by VVD** [comment]
Doesn't fixed after downgrade php to 7.4.13.

**Comment by twingg** [comment]
Hi, i found the problem, the expiry date of the cookie, that is set in js/utils.js vboxSetCookie funtion, is set to 2020-12-24, locally fixed, by changing the default expiry to 2021-12-24

**Comment by VVD** [comment]
Thanks!
But what is purpose to hardcore exact date?!

I'm not js developer, but found this:
work fine:
```
var date = new Date();
date.setDate(new Date().getDate() + 365);
var exp = (v ? (expire ? expire : date) : new Date().setDate(new Date().getDate() - 1));
```
doesn't work:
```
var date = (new Date()).setDate(new Date().getDate() + 365);
var exp = (v ? (expire ? expire : date) : new Date().setDate(new Date().getDate() - 1));
```

**Comment by twingg** [comment]
I've created a pull request, to set cookie expiry to 7 days from current date. 
https://github.com/phpvirtualbox/phpvirtualbox/pull/269

**Comment by twingg** [comment]
@VVD possibly, randomly set to 3 years of expiry, hoping, to change it in the future

**Comment by coyotenq** [comment]
Big thanks to all! twingg's patch solves de issue. For sure, was an involuntary mistake to hardcode an expiry date in a cookie.
Lets wait pull request gets passed to close.
