### ISSUE TITLE
Polling VBoxVmService is spamming the log file

### ISSUE THREAD

**Issue by VoSubat** [phpvirtualbox/phpvirtualbox#278]
As long as a user shows the phpVirtualBox web page of our Windows server, the service _VBoxVmService_ gets polled every couple of milliseconds generating at least 100kB log entries per second in VBoxVmService.log. Thousands of pages like:
```
09:20:31.357145 SQPmp    Request 279273 on socket 1340 queued for processing (1 items on Q)
09:20:31.357145 SQW01    Processing connection from IP=127.0.0.1 socket=1340 (4 out of 5 threads idle)

09:20:31.367965 SQPmp    Request 279274 on socket 1956 queued for processing (1 items on Q) 
09:20:31.367965 SQW01    Processing connection from IP=127.0.0.1 socket=1956 (4 out of 5 threads idle)
```

Recently the file grew 5GB+ big and the VM services started having several performance related side effects. After cleaning the log, everything went back to normal.
The service _VBoxVmService_ is run by Windows internal account '_SYSTEM_', wich even blocks administrators from deleting the log file while running.

I don't see any way to reduce the chattiness of VBoxVmService. It looks like phpVirtualBox opens up a new connection for each polling.

Questions:
1.) Is that expected behaviour?
2.) Is there a way to reduce the polling rate?
3.) Is it a problem in _VBoxVmService_ running on Windows and unrelated to phpVirtualBox?

[config.php.txt](https://github.com/phpvirtualbox/phpvirtualbox/files/6390901/config.php.txt)

**Comment by trasherdk** [comment]
Use `logrotate` with `copytruncate` and `maxsize`.

[logrotate(8) - Linux man page](https://linux.die.net/man/8/logrotate)

**Comment by VoSubat** [comment]
Thank you, for you hint. I totally forgot to mention: I'm running on Windows Server.
I'll try 'LogRotateWin' or some other alternative, though.  :-)
Thank you.

**Comment by trasherdk** [comment]
Sooo, you might want to close this issue, or what?

**Comment by VoSubat** [comment]
It doesn't look obvious to me why a PHP page should poll a web service every 10ms with ever new connections.
Having a workaround is not the ideal way of closing issues, especially not if no one seems to know if's a bug or not.
I hoped for a second opinion.

**Comment by trasherdk** [comment]
Here's my log files listed:
```
# ll /var/log/virtualbox/                      
total 19028
-rw------- 1 vbox vboxusers   29647 May  1 13:26 vboxweb.log
-rw------- 1 vbox vboxusers  285045 May  1 13:23 vboxweb.log.1
-rw------- 1 vbox vboxusers 3472612 Apr 13 13:27 vboxweb.log.10
-rw------- 1 vbox vboxusers 1758051 Apr 30 05:21 vboxweb.log.2
-rw------- 1 vbox vboxusers 1682274 Apr 27 13:27 vboxweb.log.3
-rw------- 1 vbox vboxusers 1671543 Apr 26 13:27 vboxweb.log.4
-rw------- 1 vbox vboxusers  369155 Apr 25 13:27 vboxweb.log.5
-rw------- 1 vbox vboxusers 2876026 Apr 25 10:30 vboxweb.log.6
-rw------- 1 vbox vboxusers  180865 Apr 21 13:27 vboxweb.log.7
-rw------- 1 vbox vboxusers  142301 Apr 21 12:52 vboxweb.log.8
-rw------- 1 vbox vboxusers 6946741 Apr 14 13:27 vboxweb.log.9
```
The biggest being ~6MB.

I could imagine, with more users, they would be bigger.

Also, polling for changes, from many users, would make the log rather busy.
The screen preview of each guest need updating, and that's probably not cheap.
![image](https://user-images.githubusercontent.com/5003891/116781206-b653b200-aaab-11eb-91f4-aaeb215a2054.png)

The log is not that busy. I did a fresh connect, and clicked on 4 different guests, and this is what is repeating in the log.
```
1128:09:11.037960 SQPmp    Request 323602 on socket 10 queued for processing (1 items on Q)
1128:09:11.038007 SQW01    Processing connection from IP=127.0.0.1 socket=10 (3 out of 4 threads idle)
1128:09:11.866216 SQPmp    Request 323603 on socket 10 queued for processing (1 items on Q)
1128:09:11.866252 SQW04    Processing connection from IP=127.0.0.1 socket=10 (3 out of 4 threads idle)
1128:09:14.038129 SQPmp    Request 323604 on socket 10 queued for processing (1 items on Q)
1128:09:14.038185 SQW02    Processing connection from IP=127.0.0.1 socket=10 (3 out of 4 threads idle)
1128:09:17.039535 SQPmp    Request 323605 on socket 10 queued for processing (1 items on Q)
1128:09:17.039571 SQW03    Processing connection from IP=127.0.0.1 socket=10 (3 out of 4 threads idle)
```

**Comment by VoSubat** [comment]
Perfect, thank you. It looks like I have some bad configuration. Your requests com much slower and only on event. Plus they are using the same socket each time.
Thank you - I'll close the issue.
