### ISSUE TITLE
vboxwebsrv not present in 6.1_6.1.26

### ISSUE THREAD

**Issue by kasumiru** [phpvirtualbox/phpvirtualbox#282]
latest distro virtualbox-6.1 for debian 10 not present vboxwebsrv binary file! only shell script. 
I cant run `/usr/bin/vboxwebsrv --pidfile /run/vboxweb/vboxweb.pid --host=0.0.0.0 --background`, see error:
/usr/bin/vboxwebsrv: 138: exec: /usr/lib/virtualbox/vboxwebsrv: not found

STR:
```
apt download virtualbox-6.1
dpkg-deb -R virtualbox-6.1_6.1.26-145957~Debian~buster_amd64.deb virtualbox-6.1

apt download virtualbox-6.0
dpkg-deb -R virtualbox-6.0_6.0.24-139119~Debian~buster_amd64.deb virtualbox-6.0

find -iname vboxwebsrv
./virtualbox-6.1_6.1.26-145957~Debian~buster_amd64/usr/bin/vboxwebsrv
./virtualbox-6.0_6.0.24-139119~Debian~buster_amd64/usr/bin/vboxwebsrv
./virtualbox-6.0_6.0.24-139119~Debian~buster_amd64/usr/lib/virtualbox/vboxwebsrv
```
!!

Testin in clear 
VERSION="10 (buster)"
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
Linux debian 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux

**Comment by Infomaniac007** [comment]
Known issue with 6.1.26 version

https://www.virtualbox.org/ticket/20479

Working after following the instructions.

Get previous version here :
https://download.virtualbox.org/virtualbox/6.1.24/
For ubuntu i took : virtualbox-6.1_6.1.24-145767~Ubuntu~eoan_amd64.deb
Extract vboxwebsrv from this folder/./usr/lib/virtualbox/

cpy vboxwebserv in /usr/lib/virtualbox/ folder

**Comment by kasumiru** [comment]
thank You for quickly answer )

**Comment by kasumiru** [comment]
closed I think
