### ISSUE TITLE
An unknown PHP error occurred

### ISSUE THREAD

**Issue by gentlemgp** [phpvirtualbox/phpvirtualbox#286]
Hey there. I have got a fresh installation of  virtualbox (v6.1.26) and phpvirtualbox (latest develop version).

I have tried several times and I always run into this error messages, while browsing to phpvirtualbox.

"An unknown PHP error occurred. This is most likely a syntax error in config.php in phpVirtualBox's folder. The most common errors are an unclosed quote or a missing semicolon in a configuration item that has been entered (e.g. location, username, or password).
Depending on your PHP configuration, navigating directly to config.php in your web browser may display the PHP error message.
If find that this is not the case, or have no idea what this error message means, please raise the issue at https://github.com/phpvirtualbox/phpvirtualbox/issues"

I have checked config.php and no mistakes were found. I have also checked installation of json and libxml extensions.

Here is my config.php for further information.
[config.php.txt](https://github.com/phpvirtualbox/phpvirtualbox/files/7303588/config.php.txt)

Please help me.

**Comment by JD-aus** [comment]
did you get this sorted ?

i am running on Debian 11 and its working fine for me (although it took me a LONG time to get it running initially).
