### ISSUE TITLE
Is there a RELEASE version of phpvirtualbox for Oracle VirtualBox >= v6.x.y available now?

### ISSUE THREAD

**Issue by kosuodhmwa** [phpvirtualbox/phpvirtualbox#287]
Hi there

MAJOR QUESTION: Is there a RELEASE version of phpvirtualbox for Oracle VirtualBox >= v6.x.y available now?

AND: Is it planned to implement the VM screen with native HTML5-Browser-based technology (Flash does not exist anmore so we all know) I think that's theoretically possible - "Proxmox" is also able to do that in its backend web GUI... so why phpwirtualbox is not...? I thank the HTML5 "canvas" element in combination with a VNC binary data strem would be the right choise - right?

Thank you very much for your feedbacks... :-)

**Comment by JD-aus** [comment]
I just updated to debian 10 last night and now i cannot get to the virtualbox ... im sure it was Version 6.1.X ... but now im not so sure

**Comment by kosuodhmwa** [comment]
hi

my question was NOT about OS vs. VirtualBox version - thus, my question was about phpvirtualbox version VS. VirtualBox version.


kind regards, jan

**Comment by kosuodhmwa** [comment]
And my question is also NOT OS-related... the VirtualBox web service (with that, phpvirtualbox does its interaction) is same und because of that idependent from os.

It's just a question of: ´VirtualBox 6.x.y Webservice <-> phpvirtualbox Version´

;-)

**Comment by kosuodhmwa** [comment]
-> https://github.com/phpvirtualbox/phpvirtualbox/issues/279

**Comment by kosuodhmwa** [comment]
Maybe somebody knows more how it currently is...?

**Comment by wagnbeu0** [comment]
I would also suggest to provide a version for VB6.x
I found this software beccause I need to share w Win10 verson via Webbrowser - but on my Debian 11.1 i Cannot get it run with VB5.2, and 6.x has incompatibilities now.

**Comment by trasherdk** [comment]
What is the problem with `6.x` ?  
I'm running `6.0.24` with no problems, and to my knowledge, there is no problems on `6.1.x` either.

**Comment by kosuodhmwa** [comment]
Where can i download it?

**Comment by trasherdk** [comment]
Do a `git clone https://github.com/phpvirtualbox/phpvirtualbox.git` and you have the latest `6.1.x` version. It's the `default` branch.

If you are on `PHP 8.0 something` you'd probably need https://github.com/phpvirtualbox/phpvirtualbox/pull/292

**Comment by kosuodhmwa** [comment]
ok thx

**Comment by kosuodhmwa** [comment]
will look on it ASAP

**Comment by kosuodhmwa** [comment]
**_"Do a git clone https://github.com/phpvirtualbox/phpvirtualbox.git ... "_**

Same as https://github.com/phpvirtualbox/phpvirtualbox/archive/refs/heads/develop.zip - right? 

Thank you for your feedback(s) :)

**Comment by trasherdk** [comment]
I don't know. I don't use 6.1
