### ISSUE TITLE
Use phpVirtualBox for VirtualBox 6.1.x with 7.0 "pre-release" Version 6.1.97?

### ISSUE THREAD

**Issue by kosuodhmwa** [phpvirtualbox/phpvirtualbox#301]
Hi there

**QUESTION:** How to use phpVirtualBox for VirtualBox 6.1.x with 7.0 "pre-release" Version 6.1.97? **Does that work, does somebody know...?**

Thank you very very much in advance for your feedback(s). :-)

With best regards,
Jan

**Comment by kosuodhmwa** [comment]
???

**Comment by jayjupdhig** [comment]
same question here

**Comment by kosuodhmwa** [comment]
???

**Comment by kosuodhmwa** [comment]
???

**Comment by thedisbo1125** [comment]
I setup a Ubuntu server test box and installing the latest beta.  I found that the vboxwebsrv is missing from the /usr/lib/virtualbox/ directory.  I checked another deb file as well as a Red Het one but missing from those as well.  It appears to be in the "VirtualBox-7.0.0_BETA1-153351-Linux_amd64.run" file, but I'll have to reinstall my test box and give it another try.
