### ISSUE TITLE
An unknown PHP error occurred

### ISSUE THREAD

**Issue by JustinsKittens** [phpvirtualbox/phpvirtualbox#303]
An unknown PHP error occurred. This is most likely a syntax error in config.php in phpVirtualBox's folder. The most common errors are an unclosed quote or a missing semicolon in a configuration item that has been entered (e.g. location, username, or password).

Depending on your PHP configuration, navigating directly to config.php in your web browser may display the PHP error message.

If find that this is not the case, or have no idea what this error message means, please raise the issue at http://sourceforge.net/p/phpvirtualbox/discussion/help/

Host OS - Windows 10
PHP - 8.1.6
VirtualBox -6.1
Apache - 2.4

Using XAMPP

My config file:
[config.php.txt](https://github.com/phpvirtualbox/phpvirtualbox/files/8713800/config.php.txt)

**Comment by h6w** [comment]
At first glance it looks like you have a comma before the closing bracket.

Line 49:

```
),   <---- There shouldn't be a comma here.
);

```

**Comment by JustinsKittens** [comment]
Ok, I'll see if these things help.
I'll be back.

**Comment by JustinsKittens** [comment]
I am back, and it still does not work.
My new config.php file:
[config.php.txt](https://github.com/phpvirtualbox/phpvirtualbox/files/8713892/config.php.txt)

**Comment by rigved123** [comment]
hey same issue

**Comment by rigved123** [comment]
can anyone help me with this

**Comment by trasherdk** [comment]
@rigved123  The `An unknown PHP error occurred` is a generic error message. So unless you provide more context, no one can help you.
