### ISSUE TITLE
An unknown PHP error occurred

### ISSUE THREAD

**Issue by JetsadaWijit** [phpvirtualbox/phpvirtualbox#320]
An unknown PHP error occurred. This is most likely a syntax error in config.php in phpVirtualBox's folder. The most common errors are an unclosed quote or a missing semicolon in a configuration item that has been entered (e.g. location, username, or password).

Depending on your PHP configuration, navigating directly to [config.php](http://localhost/virtualbox/config.php) in your web browser may display the PHP error message.

If find that this is not the case, or have no idea what this error message means, please raise the issue at https://github.com/phpvirtualbox/phpvirtualbox/issues/

**Comment by scharan** [comment]
In my case, I found the error looking at the webserver error log: Call to undefined function simplexml_load_string(), which I fixed by installing php<ver>-xml.
