### ISSUE TITLE
Error create virtual machine - Too few arguments to function IVirtualBox

### ISSUE THREAD

**Issue by rbernardes** [phpvirtualbox/phpvirtualbox#321]
After this [issue](https://github.com/phpvirtualbox/phpvirtualbox/issues/313) implementation, i try to create a new virtual machine, with follow steps:

- new
- select name/type/version
- set memory
- create hard disk (vdi)
- dynamically allocated
and then

> There was an error obtaining the list of registered virtual machines from VirtualBox. Make sure vboxwebsrv is running and that the settings in config.php are correct.
> 
> The list of virtual machines will not begin auto-refreshing again until this page is reloaded.
> 
> HTTP error: 500 error

On details:

> readyState: "4"
> responseText: ""
> status: "500"
> statusText: "error"

Nginx error:

> thrown in /var/www/virtualbox/endpoints/lib/vboxServiceWrappers.php on line 1544" while reading response header from upstream, client: xx.xx.xx.xx, server: xx.xx.xx, request: "POST /endpoints/api.php HTTP/2.0", upstream: "fastcgi://127.0.0.1:9001", host: xx.xx.xx.xx
> 2022/12/22 11:27:42 [error] 36129#36129: *8378 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "context" in /var/www/virtualbox/endpoints/lib/language.php on line 77" while reading response header from upstream, client: 172.71.11.133, server:xx.xx.xx.xx, request: "GET /endpoints/language.php?_=1671719262366 HTTP/2.0", upstream: "fastcgi://127.0.0.1:9001", host: "xx.xx.xx.xx"
> 2022/12/22 11:28:36 [error] 36129#36129: *8373 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function IVirtualBox::createMachine(), 6 passed in /var/www/virtualbox/endpoints/lib/vboxconnector.php on line 3802 and exactly 8 expected in /var/www/virtualbox/endpoints/lib/vboxServiceWrappers.php:1544
> Stack trace:
> #0 /var/www/virtualbox/endpoints/lib/vboxconnector.php(3802): IVirtualBox->createMachine(NULL, 'win2016vm', NULL, 'Windows2016_64', NULL, NULL)
> #1 /var/www/virtualbox/endpoints/lib/vboxconnector.php(951): vboxconnector->remote_machineCreate(Array)
> #2 /var/www/virtualbox/endpoints/api.php(316): vboxconnector->__call('machineCreate', Array)
> #3 {main}
>   thrown in /var/www/virtualbox/endpoints/lib/vboxServiceWrappers.php on line 1544" while reading response header from upstream, client: 172.71.11.133, server: xx.xx.xx.xx, request: "POST /endpoints/api.php HTTP/2.0", upstream: "fastcgi://127.0.0.1:9001", host: "xx.xx.xx.xx"
 
Trying with php 7.4/8.0

**Comment by BartekSz95** [comment]
I confirmed this issue on my production server. I will try check this, maybe I can fix that.

**Comment by BartekSz95** [comment]
@rbernardes I fixed this. You can download working version on my fork repository:
https://github.com/BartekSz95/phpvirtualbox_vbox70_php82

Direct download link: https://github.com/BartekSz95/phpvirtualbox_vbox70_php82/archive/refs/heads/develop.zip

**Comment by trasherdk** [comment]
I guess it's a `6.1.x` thing. On `6.0.x` this works:

```php
  /* @var $m IMachine */
  $m = $this->vbox->createMachine(null,$args['name'],($this->settings->phpVboxGroups ? '' : $args['group']),$args['ostype'],null,null);
```

**Comment by BartekSz95** [comment]
I don't support 6.0.x and 6.1.x. I'm working on 7.0.x version right now :)

**Comment by trasherdk** [comment]
You didn't tag `6.1.x` before moving to `7-0-x` ??

**Comment by rbernardes** [comment]
Great job man! Its work! php 8.0 + virtualbox 7.0

**Comment by BartekSz95** [comment]
> You didn't tag `6.1.x` before moving to `7.0.x` ??

You ask about 6.1.x, so this is my version for it:
https://github.com/BartekSz95/phpvirtualbox-vbox61/archive/refs/heads/develop.zip

PHP 8.2 support with proper fixes.

**Comment by trasherdk** [comment]
@BartekSz95 Thanks. I'll have a look :smile:

**Comment by lukje** [comment]
Hi, don't You have a versione for vboxweb 7, but with php 7 compatibility?
Sorry, but it is a week that I try to make work php8 in openSUSE and instead that process php files, propose to download it.
So I reinstall everything with php7 and it works, the official version of phpversion from opensuse repository don't create VMs.
I'm expert on Java (absolutely not php) and with RemoteBox everithing works, but the performance ...
