### ISSUE TITLE
Inquire about the technology used on this site

### ISSUE THREAD

**Issue by AbdulazizSobh** [phpvirtualbox/phpvirtualbox#326]
https://www.browserling.com 
Is this site using phpVirtualBox
If not, can you do the same with phpVirtualBox?

**Comment by trasherdk** [comment]
Probably Docker images, but ask those guys.
Domain registered with `namecheap.com` :warning:

**Comment by h6w** [comment]
I'm sure you could, but it's outside the scope of this project.
