### ISSUE TITLE
Supporting Virtualbox 7.0?

### ISSUE THREAD

**Issue by vivianlin-fea** [phpvirtualbox/phpvirtualbox#327]
Hi,

Is there any plan or working on phpvirtualbox to support the new version of Virtualbox 7.0?

**Comment by xxsamxx1991** [comment]
Look here https://github.com/BartekSz95/phpvirtualbox

**Comment by vivianlin-fea** [comment]
@xxsamxx1991 
Thank you soooo much. I'll try this. :))
