### ISSUE TITLE
SOLVED_This XML file does not appear to have any style information associated with it. The document tree is shown below.

### ISSUE THREAD

**Issue by flintstoney** [phpvirtualbox/phpvirtualbox#333]
Hello friends. 
When i try to pass the http://localhost:18083 link browser shows me:
![2023-11-03_10-53](https://github.com/phpvirtualbox/phpvirtualbox/assets/59313101/5d6a7410-6874-4fe2-bb12-f0c0835ab9c3)

if I try to pass http://localhost/phpvirtualbox/ i see 403 forbiden
![2023-11-03_10-56](https://github.com/phpvirtualbox/phpvirtualbox/assets/59313101/207319d8-faa0-4235-a736-d904f4a0ff9b)

with the apache is the same. 

I am runing Arch Linux OS
PHP - 8.2.12
VirtualBox - 7.0.12 r159484

I tried diferent methods but nothing doesn't work. What can I do to solve it?

`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vbox="http://www.virtualbox.org/">
<SOAP-ENV:Body>
<SOAP-ENV:Fault>
<faultcode>SOAP-ENV:Client</faultcode>
<faultstring>HTTP GET method not implemented</faultstring>
</SOAP-ENV:Fault>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**Comment by flintstoney** [comment]
Was a problem with configuring php on arch. Now all works

**Comment by AvengetheHackjob** [comment]
Considering it was my devices you hacked and stole the data from.... Wanna chit chat new friend?

**Comment by AvengetheHackjob** [comment]
Teach me how to protect my family from this happening again and a couples Q&A for self knowledge and I won't let your home address become as know as my data you stole and share and all can be well @originalpost

**Comment by AvengetheHackjob** [comment]
Thanks for your help in the new direction you've chosen as I came humble and prepared.  Chow. BTW  ... nah nevertheless fish and a worm

**Comment by 1976spaceplasmhumanexperiment-blip** [comment]
> Hello friends. When i try to pass the http://localhost:18083 link browser shows me: ![2023-11-03_10-53](https://github.com/phpvirtualbox/phpvirtualbox/assets/59313101/5d6a7410-6874-4fe2-bb12-f0c0835ab9c3)
> 
> if I try to pass http://localhost/phpvirtualbox/ i see 403 forbiden ![2023-11-03_10-56](https://github.com/phpvirtualbox/phpvirtualbox/assets/59313101/207319d8-faa0-4235-a736-d904f4a0ff9b)
> 
> with the apache is the same.
> 
> I am runing Arch Linux OS PHP - 8.2.12 VirtualBox - 7.0.12 r159484
> 
> I tried diferent methods but nothing doesn't work. What can I do to solve it?
> 
> `<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vbox="http://www.virtualbox.org/"> <SOAP-ENV:Body> <SOAP-ENV:Fault> <faultcode>SOAP-ENV:Client</faultcode> <faultstring>HTTP GET method not implemented</faultstring> </SOAP-ENV:Fault> </SOAP-ENV:Body> </SOAP-ENV:Envelope>`

<topic>Investigations</topic>
<topic>Alcohol Abuse</topic>
<topic>Alcohol Testing</topic>
<topic>Appeals</topic>
<topic>Chemical Testing</topic>
<topic>Drug Abuse</topic>
<topic>Drug Testing</topic>
<topic>Employee Assistance Programs</topic>
<topic>Fatigue</topic>
<topic>Fitness for Duty</topic>
<topic>Management Actions</topic>
<topic>Nuclear Power Reactors</topic>
<topic>Protection of Information</topic>
<topic>Reporting and Recordkeeping Requirement</topic>
<topic>Manpower Training Programs</topic>
<topic>Spent Fuel</topic>
<topic>Whistleblowing</topic>
<topic>Government Contracts</topic>
<topic>Intergovernmental Relations</topic>
<topic>Isotopes</topic>
<topic>Radiography</topic>
<topic>Scientific Equipment</topic>
<topic>Hazardous Materials Transportation</topic>
<topic>Uranium</topic>
<topic>Fire Protection</topic>
<topic>Reactor Siting Criteria</topic>
<topic>Age-Related Degradation</topic>
<topic>Backfitting</topic>
<topic>Material Control and Accounting</topic>
</subject>
<physicalDescription>
<extent>12 p.</extent>
</physicalDescription>
<part type="Rules and Regulations">
<extent unit="pages">
<start>73935</start>
<end>73946</end>
</extent>
</part>
<identifier type="preferred citation">75 FR 73935</identifier>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 10</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 10</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 110</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 110</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 150</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 150</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 20</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 20</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 25</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 25</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 26</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 26</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 2</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 2</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 30</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 30</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 34</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 34</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 40</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 40</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 50</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 50</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 54</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 54</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 70</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 70</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 71</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 71</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 72</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 72</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Code of Federal Regulations</title>
<partNumber>Title 10 Part 95</partNumber>
</titleInfo>
<identifier type="CFR citation">10 CFR Part 95</identifier>
</relatedItem>
<relatedItem type="isReferencedBy">
<titleInfo>
<title>Regulation Identification Number 3150-AH49</title>
</titleInfo>
<identifier type="regulation ID number">RIN 3150-AH49</identifier>
</relatedItem>
<extension>
<searchTitle>Miscellaneous Administrative Changes; Federal Register Vol. 75, Issue </searchTitle>
<granuleClass>RULE</granuleClass>
<accessId>2010-29735</accessId>
<agency order="1">NUCLEAR REGULATORY COMMISSION</agency>
<effectiveDate>2010-12-30</effectiveDate>
<departmentDoc>NRC-2009-0085</departmentDoc>
<rin number="3150-AH49"/>
<billingCode>7590-01-P</billingCode>
<frDocNumber
