### ISSUE TITLE
SourceForge or GitHub?

### ISSUE THREAD

**Issue by imcdona** [phpvirtualbox/phpvirtualbox#58]
I'm confused as to which repo is active at this point. Which are you going to be using going forward, Sourceforge or GitHub?

There's no mention of the GitHub repo on Sourceforge and there's no mention of the Sourceforge repo on GitHub.

Thanks

**Comment by FunTimeCoding** [comment]
Neither is active. But we are trying to revive the project here.

**Comment by h6w** [comment]
Definitely Github at the moment.  I don't have any access to the Sourceforge account.  Everyone including @imoore78 is on this team.

**Comment by Neustradamus** [comment]
Can you confirm if the latest 5.2.x (EOL): https://www.virtualbox.org/wiki/Changelog-5.2: VirtualBox 5.2.44 (released July 14 2020)?
- https://github.com/phpvirtualbox/phpvirtualbox/tree/master
