### ISSUE TITLE
Since this is dead, any alternative?

### ISSUE THREAD

**Issue by DeadSix27** [phpvirtualbox/phpvirtualbox#59]
See title.

**Comment by FunTimeCoding** [comment]
I want to keep it alive. With this namespace.

**Comment by FunTimeCoding** [comment]
I haven't heard back from the owner yet. #19

**Comment by FunTimeCoding** [comment]
I've also been hanging out on Freenode #phpvirtualbox for weeks, if you're interested in chatting.

**Comment by DeadSix27** [comment]
Well, the original is LGPL3 so we do not really need to hear back from him, but sure, I'll join some day, If i find the time.

**Comment by md2k** [comment]
@imoore76 you still the owner of this project or it can be considered as dead ?

**Comment by zoon01** [comment]
I get a bit sick of it as there is no alternative they way we use virtualbox on freebsd.
Now with version 5.1.26 snapshots are broken including setup of new vm's.
I really hope this project does not really die, it's code now really need some maintenance.

**Comment by Neustradamus** [comment]
Can you confirm if the latest 5.2.x (EOL): https://www.virtualbox.org/wiki/Changelog-5.2: VirtualBox 5.2.44 (released July 14 2020)?
- https://github.com/phpvirtualbox/phpvirtualbox/tree/master
