### ISSUE TITLE
Remote Console does'nt works

### ISSUE THREAD

**Issue by KhrisRen** [phpvirtualbox/phpvirtualbox#62]
Hi everyone.

In my Server Machine with Open Suse 42.3 and virtualbox 5.1.26_SUSE, I Installed Oracle Extensión but is not possible start the virtual machine with remote display option enabled, this show "Could not find the VirtualBox Remote Desktop Extension library".

Do you know about that?

Best Regards!

PD: phpVirtualbox is a nice tool, good works!!!

**Comment by mitchellurgero** [comment]
You need to install the VirtualBox extensions package, assuming you are on the latest:
http://download.virtualbox.org/virtualbox/5.1.28/Oracle_VM_VirtualBox_Extension_Pack-5.1.28-117968.vbox-extpack

Or the download page itself:
https://www.virtualbox.org/wiki/Downloads

See section that says "Oracle VM VirtualBox Extension Pack"

**Comment by raven700** [comment]
Hi,
I had the same problem on openSuse and solved it by installing **libvncserver0**
Try:
`sudo zypper in libvncserver0`
I hope it will help

**Comment by h6w** [comment]
Works for me!  Closing unless anyone else has any other reasons why it wouldn't work.
