### ISSUE TITLE
Support for Virtualbox 5.2?

### ISSUE THREAD

**Issue by e-alfred** [phpvirtualbox/phpvirtualbox#64]
Hello,

now that Virtualbox 5.2 is out, are there any compatibility problems with Phpvirtualbox?

**Comment by h6w** [comment]
Not that I can see.  I've had it running on 5.2 for a few days now and everything is doing what the box says (albeit with the annoying dialog box).  If you spot a problem (other than the version check box) please open a bug report.  I'm closing this for now.

**Comment by Neustradamus** [comment]
Can you confirm if the latest 5.2.x (EOL): https://www.virtualbox.org/wiki/Changelog-5.2: VirtualBox 5.2.44 (released July 14 2020)?
- https://github.com/phpvirtualbox/phpvirtualbox/tree/master
