### ISSUE TITLE
Error in phpvirtualbox.conf ???

### ISSUE THREAD

**Issue by MalHarwood** [phpvirtualbox/phpvirtualbox#77]
The phpvirtualbox.conf file has "DirectoryIndex index.php"

However the only file in the root directory is index.html

Accessing the html file directly works and hence modifying the apache config file also works.

**Comment by KrakenTyP-co** [comment]
#78 
Im create pull-request with change

**Comment by h6w** [comment]
PR accepted.  Thank you!
