### ISSUE TITLE
Support for Virtualbox 5.2

### ISSUE THREAD

**Issue by h6w** [phpvirtualbox/phpvirtualbox#79]
Currently in tag 5.2-RC1 in develop branch.  See here: https://github.com/phpvirtualbox/phpvirtualbox/archive/5.2-0-rc1.zip

There are a few bugfixes in develop head as well.  RC2 coming soon.

**Comment by marcelser** [comment]
I really hope RC2 is coming out soon, there's some many errors in RC1 it's not even funny. Just to list a few I came across today when I have installed it:
1.) create snapshot -> no action at all
2.) mount other optical iso image -> give unknown property 'device' 
3.) clone vm -> failes somehwere in the middle with some strange property error (clone is not created)
4.) always show "Flash is not installed" for RDP (tried all 4 browsers I have Chrome, Firefox, Edge & IE 10) none of them works, I guess this is not really browser related then cause flash is installed in all of them.
5.) is VNC supported and how to switch (if it's implemented then mostly documentation)

So most of the time I had to google around and do the stuff manually via VBoxManage cause most of the operations I tried failed miserably.

What works really well is stopping, starting and other basic stuff but that's not really hard right

**Comment by h6w** [comment]
RC2 is out now! :-D

If I don't hear anything significant, then I'll release it as 5.2.0 on 2018-02-16.

Thanks for your input!

**Comment by h6w** [comment]
A new version is now available in [releases](https://github.com/phpvirtualbox/phpvirtualbox/releases)

Specifically [5.2-0.zip](https://github.com/phpvirtualbox/phpvirtualbox/archive/5.2-0.zip)

@Robertus538 please open your suggestions as separate feature requests as I'm closing this as completed.  Yay!

Thanks for everyone's help, support, and patience. :)

**Comment by Neustradamus** [comment]
Can you confirm if the latest 5.2.x (EOL): https://www.virtualbox.org/wiki/Changelog-5.2: VirtualBox 5.2.44 (released July 14 2020)?
- https://github.com/phpvirtualbox/phpvirtualbox/tree/master
