### ISSUE TITLE
Instruction refers to phpvirtualbox.config but there is no such file in the main.zip

### ISSUE THREAD

**Issue by ndinev** [phpvirtualbox/phpvirtualbox#82]
```
1. Download zip file from GitHub project site: https://github.com/phpvirtualbox/phpvirtualbox/archive/master.zip
....
4.  Move phpvirtualbox.conf into /etc/apache2/conf-available/ * NB: The default config file makes phpvirtualbox only accessible from the localhost for security reasons.
```

There is no phpvirtualbox.conf in master.zip

**Comment by h6w** [comment]
That's because you're looking at the develop branch for the docs, but the master branch for the file.  If you want the develop branch, go here: https://github.com/phpvirtualbox/phpvirtualbox/archive/develop.zip

**Comment by jeremyakers** [comment]
The thing is: I don't really want the develop branch. I'm just following the link form Sourceforge to your Github site and those are the instructions posted there on the main landing page. I'm not selecting the develop branch anywhere in this process, it's the branch that's auto-selected... And why would the instructions for the develop branch ask you to download the master branch if the instructions only apply to the develop branch?

**Comment by h6w** [comment]
Because you can't make changes while merging, so the develop branch has to look like it's the master before it gets merged into master.
