### ISSUE TITLE
[Documentation] Notes for Ubuntu 17.10

### ISSUE THREAD

**Issue by clontarfx** [phpvirtualbox/phpvirtualbox#86]
The following are required for a successful run of phpVirtualBox on Ubuntu 17.10

Install required packages
`apt-get install php7.1-fpm libapache2-mod-php php-xml php-soap`

Configure Apache 2 for PHP 7
```
a2enmod proxy_fcgi setenvif
a2enconf php7.1-fpm
```

Restart Apache2
`systemctl reload apache2`

**Comment by tom077** [comment]
This is not about making phpVirtualbox run successfully. This is about setting up a web/PHP server. There are many possibilities to do so.

Apache2 is not a "requirement" for phpVirtualBox. You can use Nginx instead.

**Comment by tom077** [comment]
As explained in the Wiki  (https://github.com/phpvirtualbox/phpvirtualbox/wiki/Web-server-and-PHP-installation#debian), you can configure Apache2 to serve PHP without using php-fpm.

Moreover, you can't use libapache2-mod-php and php-fpm at the same time. You have to choose one of them to configure Apache2.
