### ISSUE TITLE
VirtualBox update seems to have broken PHPVirtualBox

### ISSUE THREAD

**Issue by ghost** [phpvirtualbox/phpvirtualbox#9]
Today I did an update on a CentOS server, and one of the updates happened to be an update to VirtualBox. Unfortunately this seems to have a conflict with phpvirtualbox.

Symptoms: can start, clone and move VMs, but cannot change them. Closing the dialog box there is a wheel that turns and then a time out. Inspecting the VM afterwards, one can see that the change was not registered. Thus there seems to be some lack of communication between the two.

**Comment by chotaire** [comment]
Can someone close this issue please? As of today, phpVirtualBox works fine on CentOS with VirtualBox updated from repository. This issue is 4 years old.

**Comment by h6w** [comment]
Yes.  This issue was a migration from SF and no longer applies.  Closing.
