### ISSUE TITLE
No phpvirtualbox.conf in master.zip

### ISSUE THREAD

**Issue by jeremyakers** [phpvirtualbox/phpvirtualbox#90]
Instructions say:

> 1. Download zip file from GitHub project site: https://github.com/phpvirtualbox/phpvirtualbox/archive/master.zip
> 2. Unzip zipfile into /usr/share/phpvirtualbox
> 3. Rename config.php-example to config.php and edit as needed.
> 4. Move phpvirtualbox.conf into /etc/apache2/conf-available/ * NB: The default config file makes phpvirtualbox only accessible from the localhost for security reasons. 

However the file "phpvirtualbox.conf" is not contained within the "master.zip" file downloaded in step #1, nor are there any files at all with the filename extension .conf contained within the zip file.

**Comment by tom077** [comment]
same as #82 

You are right,  the current master branch doesn't contain any phpvirtualbox.conf. That file was added in the develop branch and the instructions in develop/README.md was updated a few months ago, but these instructions won't be applicable until the develop branch is merged into the master branch.

Meanwhile, if you want to try the develop branch,  you have to download [that zip file](https://github.com/phpvirtualbox/phpvirtualbox/archive/develop.zip) at step 1.

**Comment by tom077** [comment]
> jeremyakers : The thing is: I don't really want the develop branch. I'm just following the link form Sourceforge to your Github site and those are the instructions posted there on the main landing page. I'm not selecting the develop branch anywhere in this process, it's the branch that's auto-selected... And why would the instructions for the develop branch ask you to download the master branch if the 
instructions only apply to the develop branch?

Actually, I think it would be better to remove the step 4 and 5 from the instructions (README.md).
These 2 steps suppose :
- we are using a Debian based Linux distribution
- we are using Apache as web server

There are also people not using Debian or Ubuntu, people using nginx or lighthttpd as web server, and even people using Windows.

What is your OS and your web server? Did you get phpvirtualbox working?

**Comment by h6w** [comment]
Closing as 5.2-0 was released.
